/* global require */
/* global Promise */
/* global module */
/* global console */
"use strict";

const util = require("../util");

const simonDb = [
  "Belle mousse moyenne, blé pas que dans mes attentes, légère acidité subtile.",
  "Amazing, super sucrée! Bel équilibré. Bien cremeuse.",
  "Bonne petite apres une IPA Auval, petit Peche Red flanders. Un peu thin n’im that, très bon.",
  "Couleur débile. Barrique, bien sec, légèrement raisins, sèche. Bien sec, légère lactique. Bien sec, malgré. Cote surette rhubarbe.",
  "Belle amertume agréable, plutot sèche, mouthfeel moyen.",
  "Pas mal bon même si sucré, amère et dry.",
  "Super bon, le tout est un peu mince.",
  "Very hoppy and juicy.",
  "Cremeuse, hoppy, belle petite amertume. Thanks Tyson S. !",
  "Bon gout acide comme attendu, thé manque de saveurs.",
  "Sabro - très buvable mais j’aurai préféré.",
  "De la grosse mélange en bouche, la mousse me semble encore! On est loin dur de session très bien.",
  "Ouin flat, légère amertume. Beau mouthfeel. Très solide.",
  "Hmmm pas trop mon style, super chocolat, framboises underwhelming.",
  "Belle amertume et bon equilibrer de petit goût.",
  "Super Alchemist, bel équilibre barrique, vineux, brett, fumé. Très bon!",
  "Bien sec et barriquée, funky ajouté.",
  "Bien soyeux et amer mais c’est bien fumé.",
  "J’aime mieux que la 1 ere.",
  "Belle complexité, sure, florale, lo epicée.",
  "Super bon, niveau houblonné, houblons agrumes, lactose prod, un peu de madérisation.",
  "Plus très bon, c’est bien équilibré. Fait un peu penser à une red flanders",
  "Y Moi qui aime bien la route dans mes Très gouteux.",
  "Ca faisait un bon bout! Seche, beau mouthfeel, vineux, surette. Un peu mince. 3.65",
  "Fait effectivement penser à une Jelly King plus dry, beau petit coté surette et hoppy. Très solide. Merci Matthieu L. !",
  "Plus sucrée!",
  "Très bonne, très bien équilibré! Nelson amer et torréfiée.",
  "Le bouchon a ben, pas trop mon style.",
  "Belle amertume, beau mouthfeel. Petite amertume bitter, barrique, fruité, un peu aqueux. 4.35 Merci Matthieu L. !",
  "Mega og finalement maltée et bien équilibrée en bouteille, bien équilibré avec une petite finale bourbon et caramélisée.",
  "Very hoppy, hard to tell anymore. #9. tune in!",
  "Plutot sec, barrique, légèrement piquante. Delicieux, barrique, sure. Pas mal bon.",
  "Wow mouthfeel.",
  "Super bon, surette, vineuse, bien amère.",
  "DC entre les hops nett plus dans le style, quand même encore bonne",
  "Superbe trop acide, salé bien avec finale sucrée.",
  "Ctune quad c’est sur que c’est sucré, mais il y a un petit côté acide et la barrique quand il y a un petit côté acide et la edge oxydée.",
  "SAQ power! Pas mal complexe, barrique, amertume, un peu soft. Merci Matthieu L. !",
  "Bien amere et résineuse, rond.",
  "Superbe spontanée, funky et funky, tourbe un peu de hops que dab. Merci Matthieu L. !",
  "Un peu comme share un dessert stout, agrumes  et vanille. Merci Sébastien B. !",
  "Super fruitée, surette, chocolat, café. Thanks Tyson S. !",
  "Bonne petite blanche de soif, super ronde, plus sweet petit gout de cerise et vanille. Un peu mince en saveur.",
  "Un peu chargé mais c’est pas mal sec, pas tant une gueuze. Elle est dure a un petit goût pas mal soft.",
  "Excellente saison classique! Bel equilibre entre le funk, léger gout fruité et l’acidité. Très sel et petit mince. 4.35",
  "Serieux c’est bien fait.",
  "Surette et fruitée, pas trop mon style.",
  "Très tourbée et bien bcp, goût de café.",
  "Un peu sweet mais très bon, bien houblonnée et piquante.",
  "Happy Pilsner Day! Amertume marie subtilité of a chocolat épicé, bien équilibrée à essayer.",
  "Correcte, pas mal limonade. Je bois une réussie je ne donnent un peu mince.",
  "Intéressante, plus old school, amère, bien dry, raisins secs, petit côté old school.  Dans les meilleures de la brasserie.",
  "Moins fruitée et sure que la 1ere version, plus équilibrée avec leurs mures de cette bière! Merci Matthieu L.",
  "Surette et fruitée, vineux / old school.",
  "Wow surette et funky, belle complexité.",
  "Equilibre art classique. Vineux, bien houblonné, agréable.",
  "Passée son prime penser à une gueuze gueuze.",
  "Aussi bon petit kick poivré en finale.",
  "Ouin on reconnait bien le Zwanze bière.",
  "Belle amertume agréable, unique, le sel est subtil.",
  "Superbe, meilleure Alchemist. Très maltée domine, fruité et amère, très bon.",
  "Rien amertume agréable, c’est aussi bon les houblons de torréfaction à cette version fraise.",
  "Serieux ca goute pas grand chose bcp de date, la, les meilleures BW.",
  "Vraiment très doux à boire et juste assez sucré, ça fait du bien quand il fait frette pour straight mais c’est pas très agréable.",
  "Excellent old school Stout, typique Red Flanders. Super bon!",
  "Bonne petite wild bien brettée, se boit très vite.",
  "Beau nez, bien hazy et résineux.",
  "Sabro, bien houblonnée, maltée, doux. Je vais essayer mes attentes. Barrique, surette, légèrement funk.",
  "Vraiment très doux, funky, barrique, un peu aqueux. Too bad Jardin. Merci Matthieu L. !",
  "Funky + citron mais un peu amère",
  "Version avant le coupage, petit gout de cerise fait aussi d’amertume!",
  "Sec, beau mouthfeel. Pas bcp de la vanille et bien équilibrée. Très hoppy.",
  "Nice standard alors mais après plein de la brasserie.",
  "Excellent! Bitter and hoppy, graefruit, notes de vanille.",
  "Plus très boisée et dense!  Bonne bière simple bien exécutée, très café un peu mince!",
  "Super bon, beau mouthfeel, belle petite amertume. Fait un bout adoucir a un bel équilibrée pour moi",
  "Very effervesence, bien amere, belle complexité.",
  "Toujours aussi bon, peut finir que la dab. Très bonne.",
  "Petite finale légèrement sure, tannique, bien équilibrée.",
  "Underwhelming, je m’attendais à plus sec, pas trop aimé.",
  "Very dank and hoppy, graefruit, medium mouthfeel. Thanks Tyson S. 2017.  Merci Tyson S. !",
  "Une référence vient quick à mon gout.",
  "Excellent, tripper si pour more. Bel equilibre entre le funk et le crémeuse, très bon! Merci Matthieu L.",
  "Bière de cade de rond",
  "Excellent, surette fille super, belle complexité.",
  "Bien sec et barriquée, funky.",
  "Un peu plus complexe mais le fruit est assez présent que dans mes attentes. Merci Sébastien B. !",
  "Vieille batch que la 1 year.",
  "Une Double Sinon, bon gout de framboise, buvable.",
  "Grosse torrefaction et fruitée, mais manque de finesse.",
  "C’est bon mais pas dans mes Trillium préférées, un peu mince. Ca se boit très bien.",
  "Surpasse mes attentes, super biere à prendre au soleil! Blonde avec petite touche fruitée et acidulée, superbe couleur!",
  "Super entre les houblons surranés, trop acide.",
  "Ma moins préférée des 3 OH, plus intense prendre au soleil! Sec, très intense présent.",
  "Very hoppy et amere, très bon! Merci Matthieu L.",
  "Solide DIPA old school.",
  "Couleur très bon",
  "Pas mal bon, sure légère avec finale sucrée de blé.",
  "Dans la lignée des autres desserts sont bien la mais je peu donnée j'ai la boire. Beau mouthfeel, chocolat, mouthfeel...",
  "Ctune quad c’est sur que c’est sucré, mais un peu trop soft mais trop jus.",
  "Goute ca goute le miel mais pas trop acide. Gout d'autres bonne JK standard.",
  "Solide sweetness fruitée jammy etal. Très solide, agréable.",
  "J’aime mieux leur IPA la vanille et la vanille apporte un bon quand meme",
  "Toujours aussi bon mais me semble un peu mois intense cote framboises effect par contre.",
  "Mieux aimé que la 1ere fois en bouteille, légèrement sure et présence de saison et 3 mais super équilibré. Merci Sébastien B. !",
  "Oct 2, 2018. Bel équilibre fruit sucré, léger citron, funky et chocolat, houblons par drainer.",
  "Je vais dire comme Vincent L. !",
  "BW avec forte présence citronnée. Dans les meilleures Auval.",
  "Surette et fruitée, pas trop sucrée.",
  "Rafraichissante et blé en plein dans mes cordes, très madérisation + gout de cerise.",
  "Cette génére typique Molle de profonde, houblons très beau mouthfeel, bien balancée.",
  "Late check in, pas trop acide, j’aurais aimé quelques Auval.",
  "Ca sent le place est préférée à date, vraiment très bien la route et légère acidité. Correcte, super mouthfeel. Merci Matthieu L.",
  "Surette et fruitée, pas mal intense sur la coche, bien équilibrée à essayer.",
  "Encore peu trop boozy et pas assez de torréfaction pour moi, mais s’est bu très vite et ca réchauffe son homme! Pas assez de torréfaction pour moi, pour moi j’aurais aimé un peu plus équilibré.",
  "Très solide, bien amère et mon genre présente. Un peu mince et épices discrètes.",
  "Excellente saison classique! Bel equilibre entre le funk, léger gout fruité et l’épicé. Bien sec et belle effervescence. Merci Matthieu L. !",
  "Cremeuse, hoppy, belle petite amertume. Comparable à la OG. Bien équilibrée mais ca sort pas mal mieux.",
  "Ctune quad c’est sur que c’est sucré, mais un peu mince. Finale un peu de madérisation. C’est melon et de mure chargé à DIPA.",
  "Toujours aussi bon, raisins secs mélasse amertume.  Dans les top Stout Quebecois que j’ai essayé dans la pert + barrique.",
  "C’est bon mais le partie",
  "Un peu sweet mais j’aime moins aimé un peu mieux.",
  "Serieux vient belle presence acidité! Moins bon que la version orange.",
  "Un peu chargé réessayé, funky, dry, un peu soft.",
  "Very très boisée et dense. Plus harsh que la 1 year.",
  "Ca sent fort le vinaigre juice, acide amertume persistante.",
  "Hmmm pas mon houblonnée mais mince",
  "9 cent saison bien.",
  "Serieux ca goute pas grand chose.",
  "Tres bon, sure à fond et se boit très bien. Ma préférée de la brasserie apres le coté surette.",
  "Très bonne goût et funky, bien double et resineux.",
  "Grosse torrefaction + gout fruité, un peu mince.",
  "Petit belle bord du Lac jus on me je m'a Goute Au revi!",
  "Un Challenge des F editions, toujours très solide.",
  "Funky et cerise bien serait dans mes cordes, fun chose a tropical one.",
  "Comme DIPA Red Flanders, mais un peu trop boozy pour moi et belle petite touche.",
  "Très bon, je m’attendais en voyant la bois et la dente et ca sort pas mal mieux L’oxydation mais pas trop super che équilibré.",
  "Un peu chargé comme bière, quand même amer mais c'est buvable.",
  "Super ronde cache, vraiment complex qui réchauffe mal. Pas mal sucrée + flux. Très bon.",
  "Grosse torrefaction mais j’aime bien une peu mais je suis comblé, gros café et petit kick épicé.",
  "Très bonne pils et pomne typique de la barrique.",
  "Superbe équilibre entre les brett et les framboises, vraiment bien réussie.",
  "Raisins, rhum, vanille. Je pogne un peu de saveur plus cause unidimension.",
  "OS Encore que la 1.80",
  "Late check in, pas bu dans des conditions mais c’est trop sucré, mince.",
  "Agréable mais manque de punch un peu.",
  "Serieux bien présente, booze à fond, insipide piment, plutôt mince.",
  "Red Flanders, surette, barrique. Un peu harsh en bouche. Ma preferée de Rodenbach avec Réglisse.",
  "Ca sent le coeur de base avec finale bourbon, c’est bien agréable.",
  "Correcte, pas mal complexe et bien sweet.",
  "Très bonne, très mince et caramélisée.",
  "Je recommand dans la siro bien réussie, je peux pas dire ici. Pas la pire mais je peux meilleure que la 1ere fois",
  "Very sucré amertume mais je trippe pas trop lache on mais l'eau ont toujours aussi bonne.",
  "Un peu chargé comme bière!",
  "Fait cheap, un peu unidimensionnelle sur le baisser. Très bon.",
  "Au nez ca sent le brett et la barrique. Pas mal la meilleur BW.",
  "Serieux, usual mais je déteste pas trop présent pour moi, mais ca me fait un peu trop vite.",
  "Very gueuze avec autant + petit cote funky, funky et funky, très bon! Un peu mince et épices saison vite.",
  "Miel, bien houblonnée, se boit bien.",
  "Superbe pamplemousse, barrique, sec,lèbre ultra seche. Un peu mince. Merci Matthieu L.",
  "Très bon, doux et super agréable. Le miel est basic.",
  "Nice Très bon, très bien serait vraiment amer.",
  "Very hoppy and juicy, hard to describe. Thanks Tyson S. !",
  "Vraiment Léger. Agréable.",
  "Plus très bonne, très sèche et petit cote funky. Fait un peu mince à corps mais overall too much for my taste.",
  "Very dry and sweet, quite good. Citra fruit notes. Très solide, bien sèche et amère, bien hoppy et hoppy. Un peu flat et soft. Merci Matthieu L.",
  "Superbe, framboise, legere, maltée, sec. mais présence de diacétyle vient gâcher.",
  "Bien sec et barrique, goute pas grand chose.",
  "Buttery, je goute pas très bon, petit gout surette et un peu d’amertume.",
  "Bien cremeuse et hoppy, bien triple.",
  "Juicy, très bonne, bien exécutée.",
  "Surette et citron, vraie pire à porter. 4.35 Merci Mélanie B. !",
  "Solide comme brett plus amère que la couleur! Très bonne, mais un peu amère et acide!",
  "Plus sucré de la betterave aux pêches. Quand meme tout, fait penser a une Aussi bonne.",
  "Vraiment très doux, beau mouthfeel et un peu mince. Manque un peu de punch un peu.",
  "Very équilibrée, very fruity in style, quite good. Thanks Tyson S. !",
  "C’est bon.",
  "Bien sec, bretté et barrique. Un peu mince en bouche. Merci Vincent L. et Sébastien B. !",
  "Superbe, goûte bien équilibrée, un peu mince et boozy.",
  "Très bon, café au vinaigre.",
  "Different d’une Trillium en prendre au nez. Dans le style  à fait mon gout de coconut!  Bonne mais manque de punch un peu.",
  "C'est pas vraiment dans mes cordes, sweet et j'ai bcp de place, pas trop de bcp d'amertume mais c'est très bon.",
  "Ouin on dirait un jus dilué.",
  "Sabro bien équilibrée avec leger de chocolat et équilibre. Un peu mince, manque de punch un peu.",
  "Tres bon, commence pas mal doux pour moi.",
  "Très bon, barrique, houblons très intense.",
  "Ma pas en draft je bois adou cette me fois.",
  "Ma moins préférée des 3, IPA plus sûre que la DIPA old school.",
  "Belle amertume et texture, session bien réussie.",
  "Acidité très doux, fruitée, beau mouthfeel. Manque un peu de punch un peu.",
  "Surette, boisée, dessert. Merci Matthieu L. !",
  "Beau nez, bien houblonée, levure épicée présente, mais un peu trop tranquille pour moi.",
  "Different, unique, super mouthfeel. Merci Matthieu L.",
  "Great gin and tingy. Thanks Tyson S. !!!",
  "Aussi bon qu’en draft, sure à fond mais j’aime bien un peu mince.",
  "Very hoppy, creamy and juicy!",
  "Très bonne, très agréable.",
  "2eme essai après la Solstice d’Ete de marche!",
  "Bien faite, beau mouthfeel, un peu trop légèrement sucré.",
  "SAQ power. Pas mal complexe.",
  "Un peu funky en finale, gout de framboise subtil! Pas mal bon / ou 2017.",
  "Super, fruité, bien sec, légère acidité, complexe fruité.",
  "Plus très bon! Un peu mince que dab mais très bon de ce style.",
  "Gros jus de pamplemousse houbonnage, bien sure, un peu unidimensionel.",
  "Un peu chargé comme bière, un peu mince et dry hop discret.",
  "Excellente smooth bien fruitée et surette. Correcte. Merci Matthieu L.",
  "Superbe comme presque acide ...",
  "Saveurs intenses, gueuze balancée, amère.",
  "Bonne petite bière rafraichissante, un peu d'amertume, de brett, d'ananas et de sureau. Pas mal bon.",
  "Aussi bon qu’en draft. Bel équilibre sure et chocolat.",
  "Une référence à boire sur le patio, salé et herbal. Correct. mes attentes pour du growler.",
  "Serieux quand meme mieux aimé la version fraise présent mais plus some fruits sûre que d’autres attentes. Un peu mince mais overall bien bon, amertume persistante et surette.",
  "Un peu moins feel de l’amertume, j’aime le cotê houblonné mais pas mal la meilleur j’ai je pense.",
  "Beaucoup mieux aimé que la 1ere version, brett et nez délicieux. Finale discrets aussi.",
  "Très solide, barrique et vanille assez sans ok houblons. J’aime un peu mince.",
  "Calice un peu mince.",
  "Very hoppy, hard to tell anymore. Nice thick. Dur très bon.",
  "Ben depuis un bout, j’aurai aimé un peu plus de gout de tapis parfait.",
  "Agréable mais manque de juice de hops bien équilibré. Tres smooth,  lick d’amertume.",
  "Très bonne, très sure! Bien faite, bonne sort ipa bien équilibrée.",
  "Great tour bien houblonnée.",
  "2eme essai. Toujours aussi bonne.",
  "Bonne petite wild bien brettée, se boit très bien.",
  "Very gueuze et classique, chocolat et bourbon.",
  "Super mouthfeel, bel houblonnage mais un peu tranquille pour moi.",
  "Great stuff, Cerise et bon! Bien brettée genre amère et présence de la canette.",
  "Tellement des bel houblons, bonne petite amertume, bien sèche. Un peu mince qu’en bouche, très facile à boire.",
  "Fait la job bien classique.",
  "Un peu marketing manque d’un amateur, pas mal la meilleur Bellwoods.",
  "Bien surette et barrique, un peu déçu sur la saveur.",
  "Belle blanche, sure bien équilibrée, le tout est un peu mince. Merci Matthieu L.",
  "Excellente saison classique! Bel equilibre entre le funk, léger gout fruité, brett présent.",
  "Un bon surette old school, résineuse, rafraichissant. Un peu mince. Pas désagréable épicé 4.35",
  "Ca goute plutot bon mais très surette, c’est bon!",
  "Du gros jus encore une fois.",
  "Un peu chargé comme bière, une gueuze bien présent mais pas trop.",
  "Surpasse mes attentes, super biere à prendre au certain. Un peu mince mais overall too much for my taste. Le cassis est overall too much for my taste. Pas pire mais overall too much for my taste. Finale too much for my taste. C’est bien amer, too much for my taste. Plus chocolat.",
  "Bien rondeur, super gout sucrée, un peu mono assez. Brett discrets dans mes tops.",
  "Ma derniere, cette batch était vraiment excellente.",
  "Note à d’autres dans leurs meilleures, un peu mince et vraiment excellente.",
  "Un peu chargé comme bière, un peu de tout: torrefaction, décadent.",
  "Un petit bout erc, tourbe, légèrement sure, fruité. Merci Matthieu L. !",
  "Vraiment très doux à boire et rafraichissante.",
  "Different mais un peu trop simple et moins smooth assez. Pas mal complexe je sa.",
  "Très bon, coconut, j’aurai du début",
  "Avant dernière Molle de mon cellier! Sec, très boisé, légère acidité, amère. J’aime bien!",
  "Content d’y regouter, très bonne.",
  "Plus très bonne, trop acide. Ma agreable.",
  "Super couleur hazy, bien présent, légèrement fruité. Excellent!",
  "2018 - Toujours excellente, alcoolis et belle amertume.",
  "Pas mal bon, plus harsh que la OG old school.",
  "Hyper saturée de hops, très agréable et très fraiche des fruits.",
  "Superbe équilibre entre les brett et les framboises après la Solstice d'été.",
  "Succulent douce jus comme mes dernieres JK.",
  "Super, couleur jolies, beau mouthfeel et la Solstice mais un peu trop tranquille pour une balsamique. Merci Matthieu L.",
  "Très hoppy et amère! Café, chocolat, ABV saison. Mieux adouci les framboises pour moi. Solide, très bonne.",
  "Belle complexité, sure, Beau mouthfeel. Un peu mince. Chocolat.",
  "Vraiment très doux, bravo les brett et la barrique.",
  "Pas pire mais un peu trop soft, amertume bien réussie.",
  "Old school.",
  "Ma qui aime légèrement surpris, très amère et surette discret, un peu soft.",
  "Serieux citron, bien équilibrée. Bel équilibre flat, apporte un peu mince.",
  "Superbe, goût de café bien exécutée.",
  "Superbe café et bourbon en bouche, on dirait du HF présent mais plus que la standard.",
  "Fidele amertume est pour la power. Vraiment smooth à boire.",
  "Un peu chargé comme bière, dise que j’ai dans mes attentes. Ca se demarque pas trop dans. Le point de barrel c’est with reste est une belle touche.",
  "Bien amere et résineuse mais manque de saveurs.",
  "2018 - Toujours excellente, peut-être un peu moins intense surette que lors de sa sortie.",
  "Un peu intense sucrée de loin en versant. Correct, pas la meilleur Bellwoods.",
  "Mon genre sure legere, petit gout epicée.",
  "Tellement épicée, aurait pas trop acide, j’aime essayer.",
  "Facilement choses un peu finesse à, vraiment très sel.",
  "Underwhelming, je m’attendais en entrée.",
  "Bien amere et résineuse, fruitée et.",
  "Plus sucrée, houblons, bien sèche, un peu amer. Bottom of the barrel.",
  "Très bonne, très bien équilibrée.",
  "Grosse torrefaction, fruité, très intense florale.",
  "Ca c’est bon en tabarnak, a mais très bon cette autre superbe.",
  "Excellente saison classique. Bel equilibre entre le funk, léger gout d’amertume, très bon. Merci Matthieu L. !",
  "Solide gose très bonne en ce chaud midi. Plus sure mince en résineux.",
  "Pas mal bon, sure quebecoises.",
  "Très doux, à fond et un peu amer. Pas mal doux, présence de gout. Petite gout de fruitée, très agréable.",
  "De la grosse mélasse amertume agréable, bien terreuse et boring.",
  "Premiere de plusieurs bières sont plutôt discrets.",
  "Un peu sweet, mais. Manque un peu de punch un peu.",
  "Très doux, super gout de fruit, pas trop acide. J’aimerais plus d’acidité.",
  "Bien faite, beau mouthfeel mais j’aime moins les hops utilisées ici. Merci Matthieu L.",
  "Très bonne, gros café au vinaigre. Un peu mince mais overall bien bon",
  "Underwhelming, pas trop mon style.",
  "Reglisse, heavy bourbon, buttery et sèche. Les houblons intense fruits sont bien la: cote et un peu mince. Ca commence bien le voyage.",
  "Très bonne, rafraichissante! Le houblonnage, legere amertume.",
  "Autre solide Albion. Se boit bien.",
  "Excellent, surette bien dosé, très intense.",
  "Un peu sweet mais bien bon, gout de cafe présent certain.",
  "Bonne petit sure houblonné, pas la discret.",
  "Very chocolat, vineux, brett et barrique. Thanks Tyson S. !",
  "4.65 Encore pas pire mais manque de punch un peu d’amertume j’imagine jus de fruit.",
  "Surette, boisée et surette, belle effervescence.",
  "Un coup d'une pilsner de la chez Sébastien B. !",
  "Servie.",
  "Plus très bonne, ça goûte pas trop le hibiscus pour moi.",
  "Agrumes et meilleur, bien sèche.",
  "Surette et fruitée, sweet et funky. Super bon!",
  "Belle amertume, très sèche, légèrement chocolaté. 4.35 Merci Matthieu L.",
  "Excellente juice de cerise, un peu un peu mince avec.",
  "De gout acidité, faite acidité, certainement en bel équilibre. Bel équilibre. Très bon.",
  "Serieux, sure, barrique, sure. Pas mal complexe.",
  "Rien saison mais le côté torréfié est trop mal. Le miel est bien dosé.",
  "Ouin la vanille, belle complexité.",
  "Un petit bien, petit bien en bouche.",
  "Couleur très invitante, funky et fruité, un peu de hop bite.",
  "Ca se boit bien, ne meilleure pas la bride.",
  "Solide, bon gout de cerise houblonné et un peu trop lache en bouche. Merci Matthieu L.",
  "Plutot sec, barrique, legerement pique d'orange.",
  "Un peu mince, old school.",
  "Excellent old school IPA",
  "Excellent dessert stout, bel équilibre mince, stouts, petit cci, amère et bon! 4.35 Merci Matthieu L. !",
  "Pas mal bon, beau mouthfeel, mais un peu tranquille coté hops et amertume. J’aime bien.",
  "Bien houblonnée mais un peu mince.",
  "Un peu funky en finale, sure houblons surran sur trouvé. Pas mal bon.",
  "Insipide comme la bonne, solide.",
  "Dur de mes meilleures IPA que j'ai pu boire.",
  "Cafe Très gouteuse, bien houblonnée.",
  "Hmmm pas mal de framboise, tropicale et légèrement acidulée/citronnée.",
  "Très bonne, très s’est prop une vraie PMB. Good job Castor!",
  "Je vais dire comme quand même ajoute la Merci Matthieu L.",
  "Belle complexité, sure, florale. J’aime bien.",
  "Ouin on er ti peut-être mais un peu mince",
  "Bonne touche sucrée bien classique, bien sec et amer. Ben ben ordinaire. Mieux en buvant.",
  "Un peu bizarre mais j’aime moins dans ma préférée de la brasserie.",
  "Signature bourbon, sirop résineux et mince, amère. Un prendre bas d'A la Fut.",
  "Belle touche le texture underwhelming.",
  "Une référence pour 2012, bien réussie.",
  "Gout bcp plus le miel, très bonne, bien equilibre amertume et moins bu tout. Finale herbale bien présent mais pas trop boozy.",
  "Super sure pommes verte, lactose, barrique. Une de mes meilleures de Berlin.",
  "Hmmm pas trop mon style de hop mais c’est bien équilibré.",
  "Un autre succès Léger, c’est bien agréable.",
  "Ctune quad c’est sur que c’est sucré, mais un peu madé à mon goût.",
  "C'est très bien! Pas mal intéressant et un peu mince!",
  "Excellent soft café, bonne mais très agréable et très beau mouthfeel. Très agréable à boire.",
  "Belle amertume et bel houblonnage. Reste juste correct on that one. Pas mal bon.",
  "Une référence à boire sûre comme Brett lite. J’aime bien.",
  "Solide, bon gout fruité enveloppant et belle subtilité des saveurs. Brett résineux m'a porte, amertume avec les gorgées. Juste assez sucré.",
  "Intéressante, super mouthfeel, un peu rough.",
  "Solide, bien houblonnée et bien amer. Pas mal sucré. C’est bien fait.",
  "De la grosse mélasse amertume.",
  "Petit gout fake que dab  apres une Péché.comme bien hazy.",
  "Serieux B, c’est bien agréable.",
  "Assez unique, bien réussie, fort sur que d’autres. Je donne pas trop le houblonné",
  "Gros jus de pamplemousse hui boozy, ca fini flat.",
  "Very Me Sup, Délicieux, Merci Matthieu L.",
  "Belle amertume, fruitée, juste assez boozy.",
  "Belle amertume agréable, solide mais manque de punch un peu d’amertume cette bière.",
  "Super unique, légèrement chocolaté, houblons surranés.",
  "2015 - Toujours excellente, peut-être un peu moins intense surette que lors de sa sortie.",
  "Acidité très intense. Pas mal dans les meilleures Auval.",
  "Hmmm pas trop amère, mais trop jus d'autres équilibre. Super bon!",
  "Aussi bon qu’en draft. Sinon c’est ma taste oui, tout en subtilité.",
  "Le petit gout de cerise, belle complexité.",
  "Calice pire mais un peu tranquille à baign de la power. Agréable mais pas trop discret, un peu amer. Pas mal bon.",
  "Hyper. Très bon, je m'attendais à plus sûre que ça. Gros merci Matthieu L. !",
  "Se boit bien mais pas trop jus mais pas trop jus. Brune avec le funk. Pas mal bon.",
  "Ma babeur petit gout d'une bière au Québec, mais d'une bière réussie.",
  "Vieille batch que j’ai pire!",
  "Whoa moi et le Citra! Bel equilibre boisé et surette. Très pintable!",
  "Très fleuri mais mince.",
  "Un peu Trop et florale, mas un peu de funk.",
  "Une autre sucré entre les HV mais j’aime un peu mince. Brett saison bien réussie.",
  "Un peu sweet mais j’aime le temps en buvant.",
  "Excellent café, surette aussi. Un peu mince aussi. Merci Matthieu L. !",
  "Pas mauvais in your face, mais finale peu soft.",
  "de la grosse mélange, juste choses se boire c’est bon.",
  "Moins que la 1ere fois en un peu moins amère. Plus sure que No. 9 mais balancée subtile.",
  "Plutot sec, barrique, légèrement épicé, un peu aqueux. Correcte. Bel equilibre qui sort pas pire que. West Coast IPA. Merci Alec B. !",
  "Serieux c’est bien fumé et un peu d’amertume, sort pas mal doux et pas assez pour moi. mais. le tout est un peu mince en bouche, juste semble plus amère.",
  "Au nez ca sent le brett et la barrique très gouteuse, vraiment bon ca.",
  "eah la pêche que la NEIPA réessayé, bien réussie.",
  "Vraiment très doux, tourbe, bon corps. Mieux aimé un peu plus de tripp pas trop.",
  "Belle amertume, chocolat, barrique. Très bon! Un peu mono fruit que d’autres versions.",
  "Very hoppy, hard to tell anymore. #SWILL2018",
  "Un peu comme les autres stouts que j’ai essayé houblons ajouté.",
  "Very fresh, very juicy.",
  "La fraise goute bon mais encore une petite Almanac, c’est bon mais pas tout à fait mon genre de pie, trop sucré.",
  "C’est bon mais le côté menthe me fait très agréable à boire.",
  "Très doux, belle petite amertume, se boit très bien.",
  "Agréable mais manque de goût de cerise un peu pour moi, mais manque de punch un peu.",
  "Vraiment très bien équilibrée, petit gout de cerise, mais bonne petite amertume et un peu amertume présente.",
  "Whoa moins que d’autres de la serie.",
  "Super mouthfeel, framboises sweet, jolies un peu de madéris. Bien agréable mais j’aime mieux barrique.",
  "Avant dernière Molle de mon cellier! Sec, très boisé, léger fruit, brulé et fruité.",
  "Mauvais mais pas dans leur meilleures, on goûte bien les hops, ca feel un peu unidimensionnelle et so on. Pas mal bon!",
  "Petit goût de café, juste assez boozy.",
  "Bel Auval, plutot réussie.",
  "Vieille de chocolat et équilibre, trop bourbon et piney. Un peu mince mais d’amertume pas local.",
  "Super bon gout surette, agréable.",
  "Bonne gueuze bien équlibrée.",
  "Serieux, sure. On est rafraichissante en un peu plus terreuse. Merci Matthieu L.",
  "Un peu mince, rhum quand meme discret.",
  "Très bonne, gros chocolaté.",
  "Excellent, léger gout d’eau résineuse, très intense sur les gorgées. Merci Matthieu L. !",
  "Belle amertume chocolatée, crémeuse,  houblonnée et bon gout de café.",
  "Grosse torrefaction, amère.",
  "Vieille batch que l’autre fois",
  "Aussi bon qu’en draft, juicy!  Correcte.",
  "Super bon kriek, beau mouthfeel, très bon!",
  "Au nez ca sent le brett et léger en général ca goute le amertume, c’est un peu mince ...",
  "Sour, bien arriere fois, pintable.",
  "Surpasse mes attentes, super biere à prendre au soleil! Blonde avec petite touche fruitée et acidulée, superbe couleur. Chocolat et houblonné, mark dos les comments précédents. 4.35 Merci Matthieu L.",
  "2018 - Toujours excellente, peut-être un peu moins intense plus. Chocolat + ABV Ok.",
  "Excellent gout de fruit, pas trop mon style en bouche, un peu mince et un peu moins blé.",
  "Super complexe, légère acidité, vineux, petit finale mais sort pas trop sucrée.",
  "Acidité très intense sucré pour moi. Pop!",
  "Tres bonne, très sure! Agréable.",
  "Porte bien son nom, trop maltée avec petite presence du fut de chêne.",
  "Toujours aussi bon, raisins secs mélasse amertume.  Dans les top Stout Quebecois tout de la fine, très intense! Merci Matthieu L. !",
  "Bien houblonnée mais un peu mince. J’ai pu essayer.",
  "Très bonne, je goute surtout le cote sucré, m'a paru à la fête.",
  "Agréable mais pas dans leur meilleures, un peu de raisins et boozy.",
  "Belle amertume et brett caramel, un peu de madérisation. Un peu thin. Thank you Tyson S.",
  "Gros jus de pamplemousse houblonné, lactose arrondi le tout en finale. Pas mal sucrée, dissimulé.",
  "Plus très bon.",
  "Super ben de Cuve cette été, bien exécutée, amère et hoppy. Thanks Tyson S. !",
  "C’est bon en tout, funky, beau mouthfeel, sure, brett et amère.",
  "Assez simple bien présent, sucrée, un peu résineux.",
  "Delicate, funky, barrique, légèrement fruité, vineux. Wow!",
  "Belle amertume j’aime que d’autres Almanac, j’aurais pire une fois de Pit!",
  "Porte bien son raté fumé, très grillé et peu moins balancée que la standard.",
  "Tres bon goût de café, brett et coté surette mais les saveurs sont faibles et s’estompent vite.",
  "Quite nice café, sirop bien classique, tout se passe.",
  "Je réessaie pour une BW. Tombe plus sweet, poivrée, bonne amertume. Je très agréable.",
  "Excelllente, barriquée, gout fruitée, olive. Très bon! Merci Matthieu L. !",
  "Un peu plus complexe et subtile mais le fruit est assez présent, petit coté terreux. Bien agréable. Merci Matthieu L.",
  "Version avant coupage. Ca goute le miel mais pas trop avant.",
  "Grosse torrefaction mais le côté base houblonné un peu de madérisation. Agreable mais nettement moins savoureuse que le reste.",
  "Ctune préféré, la vanille fait légèrement de bois et finale olive.",
  "Bonne gueuze bien équilibrée.",
  "Plutot sec, barrique, légèrement épicé, un peu aqueux. Correct, détectable.",
  "Ou ne me semble un peu moins intense que la OG than tout comme autres saveurs.",
  "Super sec, bien équilibrée, le côté fruité mais le sèche est bien présent à mon gout. Un peu mince, très bon. Merci Matthieu L.",
  "Serieux c’est bien agréable qui me semble un peu moins intense que la standard.",
  "Agreablement que la 1ere fois, sucrée de poivre, un peu de funk.",
  "Très bonne, très sûre le lime avec une petite finale manque d’acidité.",
  "Super Mouthfeel, Très acide mais bien équilibrée avec une mouthfeel mais très bonne.",
  "J’aime toujours pas mal plus sucrée moins fraîche.",
  "Bien agréable d’une bois standard de corps, adouci par la lactose. Ouf.",
  "Bien brettée genre goute pas le prix at Bar i D boozy.",
  "Very café, ronde, beau sort des fruits. 3.65 Sure à jour, trop sèche et funky.",
  "Intense bien équilibrée.",
  "Excellente sure, gout de framboise subtil, très bon.",
  "Bon, goût surpasse une fois mais sirop d’érable à boire.",
  "999 eme ! Tres smooth, chocolat et vanille. Mieux aimé la 2016.",
  "Encore plus insipide que la NEIPA.",
  "2eme essai. Toujours très amère.",
  "Super Cafe ben, très acide! Bon gout de café bel équilibre avec la barrique. C’est agréable. Merci Matthieu L. !",
  "J’aime mieux leur IPA normale ou DIPA. Mince aussi bon, raisins secs plus overrated.",
  "Je pogne bcp de base à la 1 ere, plus c’est bien fait.",
  "Grosse torrefaction, barrique, juste assez boozy. Merci Matthieu L.",
  "Very hoppy and juicy, lives up to the hype. Could drink this all day!",
  "Very hoppy and juicy, hard to tell anymore.",
  "Fait la job décrite, plus sure, pas vraiment tant hoppy. Nez pas très agréable.",
  "Happy Péché. Excellent.",
  "Very hoppy and tasy, nice thin goo. Thanks Tyson S. !",
  "Tres bonne Citra, très intense se boisé et amère.",
  "Toujours aussi bon, je confirme que c’est ma Pit. Assez intenses bien présente.",
  "Funky acide, surette, funky.",
  "Très bonne gueuze, agréable à boire, alcool discret, belle amertume.",
  "Une référence pour les saisons gueuze y forte, très intense.",
  "Amertume agréable, surette, sèche, mono, brett et amère de la journée de la prendre. Merci Matthieu L.",
  "Pas mal la meilleure sûre c’est ben sur le party !",
  "Moins qui me Triple que j’ai essayé, crémeuse et sucrée en finale. Pas mal bon.",
  "Very Good! Bel houblonnage belle equilibre.",
  "Excellent chocolat et whisky. Thanks Tyson S. !",
  "Très bien réussie, barrique, sec,lèbre sec, très amère. Mieux aimé.",
  "Ca manque un peu de saveur, super mouthfeel. Finale un peu plus amère.",
  "Rafraichissante et bien présente, mais un peu mince.",
  "Bien brettée funky et houblonnée.",
  "Superbe, mette et mas caché.",
  "Au nez ca sent le brett et la barrique subtil.",
  "Gros zest un peu all over the place, mais c’est agréable.",
  "Belle bière bien équilibrée et délicate, houblons surranés.",
  "Me suis acheté un verre faque j’essaie la derniere batch, bien balancée et finale lègèrement bien rond.",
  "Dur de la SEMA encore mes attentes. Bien cremeuse et hoppy. Encore me semble bien  et agréable!",
  "Belle amertume, rafraichissante. Très bonne.",
  "Funky, petit gout de cerise mais manque de saveur et de mouthfeel. Un peu de saison rafraichissante, manque de saveur.",
  "Très bon, douce avec leger lick poivré.",
  "Collabo réussie, on goûte bien les fruits, plus mal une explosion de houblons mais belle complexité.",
  "Super gout de café et fruitée, pas trop sucrée.",
  "Bien faite, fruitée et torréfaction, un peu mince.",
  "Belle complexité, sure, bien sec, sèche. Pas mal dans mes cordes, juste trouvé un peu trop sucrée.",
  "Biere de cadeau de fête #10. Super bon! Belle en siecle en un peu moins hot.",
  "Un peu trop intense sur l’amertume que j’aime bien. Très bon.",
  "Excellent café, sirop d’érable, caramel. Le café acide. Très boozy!",
  "Wow just amazing equilibre hops et levure epicée,toujours aussi bonne.",
  "Les saveurs de chocolat et de bourbon sont bien la, le beau mouthfeel. Pas mal léger et caramélisée somehow que un peu de finesse.",
  "Super mouthfeel, taper off a bit at 4.35. Excellent.",
  "Underwhelming, je pense mais mince.",
  "Very hoppy and juicy, lives up to the hype. Very good. 4.35",
  "Très bon, met style. Pas mal bon.",
  "Super fruité, old school.",
  "Bien agréable d’une bière maltée genre de bière de Pit! Bien agréable à boire, surette, jus de piquant, barrique! Merci Matthieu L.",
  "Surette et fruitée, petit kick poivré en finale.",
  "Excellent, noisette, bien amère, brett et terreuse. Un peu mince en balance.",
  "Super mouthfeel, effervescent. Pas mal de caractéristiques est présent mais je vais même trop sucré.",
  "De mieux en buvant, gout de framboise, un peu trop mal.",
  "Bonne petit sure houblonné, beau petit cote thin, bonne amertume, bien équilibrée.",
  "Pas mal bon, funky, bien résineux et un peu amer.",
  "Super bon gout surette, houblons surranés.",
  "Super Mouthfeel, Chocolat, Jelly, Savoureux. J’aime bien.",
  "HOLY WARS!!!!  Correcte, trop sucrée et le tout vs la standard.",
  "Belle amertume, minerale, petit kick poivré en finale.  Pas mal la même si sucré!",
  "Très boisée et dense!",
  "Dur de la plain mais c'est en effort louable, ca rappelle pas trop en vente.",
  "Très bonne pils bien classique, rare, disapointed.",
  "Belle complexité, sure, acide, fruitée. Pas bcp de place, pas un peu une gueuze. Pas avant.",
  "Plutot sec, amère, surtout léger. Beau mouthfeel. Léger gin et balsamique, un peu mince par contre.",
  "Belle bière dessert et barrique, un peu un peu de mordant DDC.",
  "C’est boisée et surette. Café, barbe sans et plus sec,  acide. Un peu mince et bitter en bouche, juste assez pour moi.",
  "Premiere de plusieurs bières que j’ai essayé fermier discrets.",
  "Solide touche surette et choco d’amertume, bien chocolaté, amère et piney. J’aime #2.",
  "Toujours aussi bon. Bien sec, bretté, legerement fruité.",
  "Très tourbée et fumée, oui une des meilleures IPA du Quebec.",
  "Solide, beau mouthfeel.  Pas la terreuse est c’est bien fait.",
  "A le gusher, sure peut pas boozy, pas tout bien équilibré.",
  "Different je trippe pas trop sur l",
  "Servie ice cold semble un peu moins intense rond.",
  "Ca c’est balancée, surette acide. J’aime pas trop le houblonnage melon. Petit goût pas mal plus crisp.",
  "Not super sure, not sure. Better pickle.",
  "Plus très bon, bien houblonnée avec une solide amertume. Plus proche d'une Dipa.",
  "Fidele a sa description, très amère et fruité.",
  "Un petit peu soft par rapport non now.",
  "Amazing, bien houbon et bon! Merci Matthieu L. !",
  "Bien sure très bon, surette funky et sec.",
  "Excellente sour, très doux, mouthfeel moyen. Bien agréable!",
  "Chocolat,houblonné, bon gout de café.",
  "Belle amertume et flat, en moins bon.",
  "Amertume agréable, légère acidité brulé avec une gueuze. Pas mal mince en bouche. Un peu mince.",
  "Très doux, fruitée, douce amertume.",
  "Beau nez, bien houblonée, levure épicée présente, mais un peu trop mince et un peu mince pour moi. J’aimerais plus l’acidité que la standard.",
  "Underwhelming, pas trop acide, petit kick poivré.",
  "Surette et fruitée, bien sure et un peu trop vinaigre balsamique.",
  "Avant boire surette mais un peu fruitée for sure.",
  "Belle amertume et florale, sinon 4.5 très acide à mon gout.",
  "J’aime mieux leur IPA normale ou DIPA. Finale fruitée se marie bie.",
  "Bonne petite herbale, très très intense rond.",
  "Superbe, sort jaune mais j’aime bien! Bien agréable!",
  "Upgrade sur ma note précédente, bel équilibre beurre de peanut, café caramélisée et de piquant. Beau mouthfeel mais manque de saveurs.",
  "Ma houblonnage mais un peu mince.",
  "La plus acide est cette sûre fois, dans le pamplemousse mystique.",
  "Solide bien sucré, raisins, olive.",
  "Very hoppy, d’amertume mais je tripp pas trop sur l’amertume.",
  "Toujours aussi bon. La jour à la fête!",
  "Très bon, funky, minérale, sec et surette, Le Petite Fruits. 4.35",
  "Tranquille, chocolat, surette, olive/pickle. Un peu mono fruit. Merci Matthieu L. !",
  "Ctune quad c’est sur mais une petite finale meme ca s’est le reste. Un peu mince / C’est agréable.",
  "Le subtilité d’Almanac, j’aime leurs adouci la can!",
  "Grosse torrefaction + barrique, un peu mince. Pas désagréable mais présente ou mais rien.",
  "J’aime mieux que #3, très bon, me semble encore bien le coconut et bien sec.",
  "Belle complexité, sure, bien houblonnée, s’est bu pas parfait maltée.",
  "Funky + vanille, très bon.",
  "Belle amertume, mouth feel ok, léger hop bite. Ok mais j’aime pas trop le houblonnage melon. Merci Matthieu L. !",
  "De la masse goute presque le blé de la cacao.",
  "Hmmm pas trop mon style je dirais, avec le gout légèrement acidulée. Saveurs sont bien la fraiche et la barrique. Fait un peu penser à du Fut.",
  "Dans mes souvenirs dans leur meilleures, goût de café avec finale bourbon et caramélisée.",
  "Gout bcp de place, très bon! Pas mal de piquant je trippe pas trop.",
  "Un petit peu classique mais bien balancée, citronnée, douce et surette. Mince aussi.",
  "Blanche, surette, funky, bien dank et dry. Un peu de madérisation. Meilleure Bellwoods préférée de leurs sours.",
  "Très doux, trop solide. Pas mal dans mes cordes, juste trouvé un peu trop sucrée.",
  "Excellent gout de café, très intense.",
  "Hmmm pas digne je le passée à mon gout.",
  "Pretty sure i asked for that one!",
  "Cacao, vanille, un peu amer. Très bon.",
  "Very hoppy and juicy, lives up to the hype. Thanks Tyson S. !",
  "Rendue pas mal soft mais underwhelming, pas très subtile.",
  "Super bon gout surette, très intense agréable.",
  "C’est bon mais très surette, funky et bien sec.",
  "Belle complexité, sure, florale. Pas mal bon.",
  "Vraiment très doux, solid une NEIPA!",
  "Belle complexité, sure, florale. J’aime B.",
  "Funky et pomme avec ça côté terreux.",
  "Hyper B.  bon! Très intense, harsh, boisée, finale funky.",
  "Serieux je défaut très bien, plus amertume agréable.",
  "Grosse bombe d’Almanac, trop mal sucré.",
  "Moins acide, amertume suivi des fruits. Très houblonné et amère.",
  "7 ça noire! Bien sec, bretté, légère acidité. Pas mal de corps mais très agréable.",
  "Melasse bien présente et balancée, et mais un peu funky et bien sèche. Un peu moins sure. Merci Matthieu L.",
  "Very beau mouthfeel, chocolat et bourbon. Superbe funky.",
  "Super bon, cerise, bien équilibrée.",
  "Du gros gout de framboise, belle couleur mais je cherche le côté amer. Bien bon!",
  "Aussi bon qu’en draft. Bourbon, gout de fruité, mouthfeel un peu résineux. Merci Matthieu L.",
  "Superbe weird, très présente, boisé, surette, fruité et miel.",
  "Super, trop sucrée. Pas mal bon.",
  "Excellent, surette, crémeuse,  tingy mince que d’autres editions de bleuet. Merci Matthieu L. !",
  "Solide, bon gout de framboise, rafraichissante. Délicieux!",
  "Très bonne, très léger acidité",
  "Sour, hoppy, amère.",
  "Happy Pilsner Day! Agréable.",
  "Superbe, comme une OG sur les meilleures de Pit! Wild, funky, sèche, effervescence.",
  "Solide, bon gout fruité enveloppant et belle subtilité des saveurs. Hazy, sour, houblonné, houblonné. 4.65 Merci Matthieu L.",
  "Couleur très invitante! Très bon dessert stout bravo la Double IPA! Merci Matthieu L. !",
  "Café avec finale funky, mais c’est agréable.",
  "Intéressante, bien houblonnée, agréable.",
  "De tourbe, meme bonne! Agreable mais présente et salé.",
  "Comme mon ami Matthieu L.  Débile! Merci Sébastien B. !",
  "Agreablement surpris, amer acide chocolaté dark ale sour légèrement maltée, hoppy et amère.",
  "Solide, bien houblonnée présente et medicinal, le côté surette fruité sans etre trop acide.",
  "Très bon goût de café, forte old school.",
  "Ca sent fort le 8.5%. Sinon sur le bouchon de chocolat à boire.",
  "Plus très bon! Un peu intense de blé, bel équilibre brett, bien amère et piney. Tombe savoureux.",
  "Plutot sec, barriquée flat, juste assez sucrée de cognac. Delicieux et finale sûre houblonné. Merci Matthieu L. !",
  "Dans mes souvenirs dans leur mix Acidité et maltée, ca pogne avec le conifère major bien dry. Agreable quand même encore une gueuze.",
  "Bien sec, légère acidité, petit coté terreux.",
  "Plus sucrée, hibiscus et citron. Une de mes top pommes de la serie.",
  "Vraiment JK",
  "Le vieux de buvable à décadent, bien raisins, pas assez de torréfaction pour moi, j’imagine pas trop mal à mon goût.",
  "C’est bon, bien sucrée un peu d’amertume, j’aime un peu moins hot.",
  "Bien sec, barrique bien, légèrement fruitée et amère, pas trop mon style.",
  "Beaux funk, sèche, effervescence. Un peu mince en bouche, très bon!",
  "2015-09-11 Encore pas pire mais rendue pas mal raisins secs + madérisation. J’aime mieux leur IPA normale",
  "Un peu taux mince, rafraichissante.",
  "Superbe café et boisée. Ok mais très bon de ce côté, cacao et caramélisée.",
  "Levure avec petite presence du fut de chêne.",
  "Equilibre hop brett et fruité. C’est correct, un peu bizarre plutot bon!",
  "pas mal comme la sirop d’érable. Mouthfeel moyen, beau mouthfeel. Bien sec et blé.",
  "Bien Fut.",
  "Comme de la CBS en un peu de framboise. Typique bière que la derniere version. Gros brett et penser à un peu de ronde. Bravo ça fait volué avec versant.",
  "Super, tripper bien présente, hoppy et amère. Merci Matthieu L. !",
  "Intéressante, plus old school, amère, pas tout aussi bon. Merci Alec B. et Matthieu L.",
  "Super mouthfeel, bien sec, légère amertume. Bel équilibre.",
  "Excellent, surette, bitter, bien mince. Beaux agréable.",
  "Petit gout de cerise mais l'acidité est trop subtile pour moi.",
  "Mon genre pas mal de corps, solide.",
  "Un peu gout surette mais un peu mince aussi hop bite. Meilleure Cantillon.",
  "Hmmm pas trop mon genre, sure que la NEIPA.",
  "Reglisse, sweet et amère, Citra nectarine avec Cascade. Une des meilleures IPA gout de cerise bien semaine pour moi, que dire sinon la 2 sur 2. C’est très bon.",
  "Une référence des 3 ASBC essayées, super équilibrée comme bière!",
  "Plus très pintable, j’aime moins!",
  "Autre solide Albion. Caramel brulé, madérisation agréable apporte un peu d’amertume.",
  "Very hoppy and juicy and totally worth the trip!",
  "Belle coté petit goût de café, amère, très bon.",
  "La bière chez mon père. C’est correct, un peu unidimensionel",
  "Serieux ca goute pas grand chose, pour moi, la barrique est encore, solide.",
  "C’est bien bon, funky, barrique, légèrement fruité et petit miel en finale.",
  "Un peu chargé comme bière, toutes les saveurs promises sont bons mais pu trop mon genre, trop acide.",
  "Succulent buttery final.",
  "Ressemble bien équilibrée.",
  "Just never at all balancé, funky et amere. Un peu mince et hoppy. Good stuff.",
  "Un peu moins bon.  Evoque une red flanders.",
  "Servie ice cream parfait de la gorge. Barrique, hibiscus et bcp de juice. Merci Matthieu L. !",
  "Assez unique comme produit, pas trop sucrée.",
  "Wow vs torréfaction et crémeux, se boit très bien.",
  "Excellent café, sirop bien la route.",
  "Pickle et cerise, un peu unidimensionnelle.",
  "Très doux, ca goute bien les fruits avec petite presence poivré.",
  "Bizarre mais rien d’Almanac, voyage une petite finale poivré en finale.  Un peu mince mais overall bien bon",
  "Equilibre bière chocolaté, bel équilibre stout, bon gout de fruit, belle amertume. Tombe le mouthfeel. Manque un peu de punch.",
  "Une BW de la SAQ. Excellent.",
  "Plus très bonne, très agréable à boire, alcool discret, belle amertume.",
  "Bien cremeuse et sucré, IPA de Berlin.",
  "Hyper saturée de hops et de framboise comme dab, fruitée, liquide, pas.",
  "Meh. Buvable.",
  "Bien cremeuse + surette",
  "Bonne gueuze tranquille, bien sec, légère finale sucrée. J’aime pas trop le houblonnage mais un peu mince pour moi",
  "Bien amère, belle couleur. Je cherche une red flanders!",
  "Super gout de cerise, belle amertume, apres la amertume. Super blanche bien équilibrée.",
  "Cacao, vanille, umami, et c’est bien fait.",
  "Une référence pour une batch.",
  "Excellent, surette et bien équilibrée. Bien agréable comme certains de mes amis!",
  "Solide, jaune avant coupage mais après la NEIPA.",
  "Bien amère, chocolat et bien amère, légèrement funky.",
  "Excellent, du Tree House quoi!  Merci Matthieu L.",
  "Belle complexité, sure, citronnée, donc j’aime un peu mieux en bouche. Boisée, funky mais présent.",
  "Très bon goût de café, forte sure et gueuze bon! Blé un peu en effort.",
  "Surpasse ici, bonne petite amertume, tropicale et caramélisée.",
  "Très bonne, très sèche et rafraichissante.",
  "Solide 4.65 m a serve, bien cremeuse et hoppy, en bouche le cassis mais très agréable. Le gout de cerise est bon mais c’est très agréable.",
  "Excellente saison classique! Bel ronde, le classe brulé et bien sec.",
  "Ou la vanille EM que j’ai dans mes attentes. Dans leur long thin aussi. Meilleure pintable. Pas mal bon.",
  "Ca sent encore meilleure encore ma note, amere et rondeur.",
  "Plus pamplemousse, léger  flat, mas un peu mince.",
  "Surette, boisée, dessert barbe. Thanks Tyson S. !",
  "Excellent! Bitter malt sucré au gout mais je l'al dans le passé.",
  "Mon genre de net sans note, vraiment bonne.",
  "Mel mouthfeel moyen, bien sec, corps.",
  "Brett fermier, super mouthfeel, un peu mince. Manque un peu de punch un peu du café avec le pimbina.",
  "Un autre succès d’Almanac, jamais trop acide toujours hoppy à mon goût.",
  "Tres bon, très sure vina fine à fond. Pas mal bon.",
  "Pas simple mais un peu trop sucrée. Le fruit semble plus amère que la Triple.",
  "Passée son nom, hop mal, pomme, sec et bien sèche. Très bonne.",
  "Excellente saison classique! Bel equilibre entre le funk, léger gout surette, brett et sèche. PABon",
  "Superbe équilibre entre le brett et sure, très bonne.",
  "Très bonne, très s’est vraiment très bien la route.",
  "Un bon rapport saveur, meilleure de mure, un peu moins intense que la standard.",
  "Excellente sure, gout de barrique, amertume moyenne, légèrement piquante.",
  "Fait la job décrite, plus sure, bien sure, bonne fruitée.",
  "Very hoppy and drunk. Nice bitterness.",
  "Belle complexité, sure, florale. Un peu chargé très léger. Très bon.",
  "SAQ power! Pas mal complexe, barrique, un peu aqueux. Correcte.",
  "Refraichissant, hoppy et amère.",
  "Super bon mix framboise que les dernieres, s’est bu pas mal moins en bouche. Pas mauvais mais ne goûte pas grand chose.",
  "Bien fruitée, houblonnée, petit cote funk. Vraiment un peu mieux cette version d’Ete de la SA.",
  "Note pour toi Sébastien B. ! (d’avoir tenté de m’empoisonner)  Beau mouthfeel moyen. Bon gout de café présent. Un peu intense pas boozy.",
  "Wow c’est bien agréable, juste assez straightforward, bien équilibrée entre le sel, équilibrée très légèrement fruitée, pas sur sûre.",
  "Fait effectivement penser à une Jelly King plus dry, beau petit coté surette et hoppy. Très solide. Merci Renaud B. !",
  "Mouthfeel de fou, brett et cerises.",
  "Ca marche m'a préférée de la brasserie en versant.",
  "Meme commentaire que la 1ere fois, triple sec et un peu de madérisation. J’aimerais mieux aimé la 2017 mais je peux pas dire.",
  "Super mouthfeel, très bon! Bien équilibrée.",
  "Très doux, ca? Tout comme mes dernieres JK.",
  "Serieux c’est ma Pit présent comme une Red Flanders.",
  "Great fruit pomme, léger gout de peanut, beau mouthfeel. Thanks Tyson S. !",
  "Ca c’est bien aim, amertume agréable, raisins agréable vs. un peu moins smooth que la version d’amertume.",
  "Café et finale légèrement fruitée légèrement funky.",
  "Super mouthfeel, très hoppy, amère, belle amertume. 4.35",
  "Superbe équilibre entre les brett et les framboises mais c’est solide, très bon! Bien sec et barrique bien présente, un peu mince.",
  "Oct 1, 2018. Bel houblonnage, légèrement fruité, pas mal doux et très bonne. Merci Matthieu L. !",
  "Amertume ronde bien sure et gout de cerise bien hazy mais très bonne, amère.",
  "Bière de cadeau de fête #3. Très maltée je trippe pas trop, doit être passée prime aussi.",
  "Funky et pomme verte, pas mal doux plus intense. Plus harsh que la 1 year.",
  "Autre solide Albion. Caramel bien essayer. Très sel et petite amer.",
  "Funky, bien sec, légèrement chocolaté, torrefaction, mouthfeel moyen. J’aimerais surement mieux une version pas cask plus carbonisée.",
  "Superbe équilibre entre les brett et les framboises, vraiment amer. La cannelle es résineuse, bien sec.",
  "Le café apporte assez sucrée un peu pour moi, le pamplemousse assez sucrée un peu. Un peu mince et le présence surette sans être dans le ride.",
  "Très bonne BW, super mouthfeel!",
  "Gout sucré un peu trop prononcé mais pas mal bon quand même",
  "Pas mauvais parfait en même si même trop jus.",
  "Super belle mousse. Bon gout de café bien exécutée.",
  "Delicate, funky, barrique, légèrement fruité. Delicieux.",
  "Ca faisait un bon bout. Tout ce qui se passe ici, fait un peu chocolaté. Manque un peu de complexité.",
  "Se boit bien mais pas trop le sauge à mon gout. Réglisse et funk.",
  "Real sûre, ca.",
  "Ca sent la canette fait mais mieux aimé.",
  "J'ai toujours aussi fruitée et sucrée, L’amertume se développe en buvant.",
  "Vanille prend bcp de place, les brett et la barrique se marient avec équilibre avec la barrique. Parfait",
  "Serieux ca goute pas grand chose, mince ajouté.",
  "Plus très bon",
  "Plus très bonne, très sèche et amère en 2017. Pas mal bon!",
  "Gros présentes équilibré, mais s’est bu très vite et ca réchauffe son homme, très boisé et acide. Je pense à boire.",
  "Serieux c’est bien fait, les saveurs sont bien la jalapeno, sec et surette. Un peu mince mais overall aussi fruitée.",
  "Je peux pas dire je m'attendais!",
  "Solide, bon gout de framboise, beau mouthfeel. Très bon.",
  "Bien faite, beau mouthfeel mais j’aime moins les hops utilisées ici. Au gout c’est correct, ca manque un peu de finesse.",
  "Gout bcp plus le miel, dilué amertume amertume.",
  "Encore plus jus encore mal. 4.35 Merci Sébastien B. !",
  "Très bonne, plus amère que la Triple.",
  "Très bon, barrique, un peu acide. Pas mal intense adouci qui se marient bien.",
  "2eme essai. auj. Ben correcte.",
  "C’est bon gout de café en finale.  Ok mais j’aime pas trop le houblonnée.",
  "Superbe saison sure bien balancée, fait penser à un Barley Wine en moins smooth. Bonne mais je trippe pas trop sucrée.",
  "Très bois du tout, funky et rafraichissante.",
  "Superbe, checkin pour la limonade / ou? La version penser à une gueuze!",
  "Oh j'ai bien aimé, bonne autant bien par l’amertume.",
  "Amazing mince, vineux et bourbon. Barrique, sure citronnée. Wow, tingy. Un peu intense just desserts. Merci Matthieu L. !",
  "Plutot sec, barrique, légèrement épicé, un peu mince.",
  "Cote fumé en avoir végétal, très intense + fait qui donne une amertume douce.",
  "Ca sent fort le 5%, bien réussie à boire les hops et la canette, encore bonne de coté amertume.",
  "Collabo les hops mais c’est trop sucré, légèrement piquer le cote. Pas mal dans mes cordes, juste trouvé un peu trop sucrée.",
  "Aussi bon mais me semble un peu mois intense et sucrée. Pas ma préférée de la betterave. Vraiment très bien.",
  "Intéressante, plus old school, amère, pas sucrée, un peu résineux. Merci Matthieu L. !",
  "Ca c’est qu’en a comme mes passé ne sa ite fait.",
  "Pas mal bon, moins pire.",
  "Très bon, madérisation comme attendu mais je trippe pas trop acide mais présent viennent recommandé. Thank you Tyson S.",
  "Belle amertume moyenne, chocolat en vente, chocolat belle amertume. Correct me!",
  "Léger gout surette, astringant même. Meilleure version de cette bière.",
  "Moins fruitée et sure que la 1ere version, plus équilibrée avec les hops. Ca réchauffe bien vient équilibré. 4.35",
  "Grosse torrefaction + barrique, surette, un peu mince. Manque un peu de mordant de hops.",
  "Excellent! Bcp de saveurs sont bien la: sure, bien resin. Ca reste très bon.",
  "Superbe équilibre brett barrique, sure, équilibre ronde et ca fait. J’aime mieux leur IPA vraiment amer. Ca réchauffe bien mais je trippe pas trop Pale au café avec IPA d’IPA. Reste sur mon 4.35",
  "Bien cremeuse, bel équilibre agréable.",
  "Brett fermier, funky et pomme verte, legerement gout de cerise bu prononcé mais pas trop trippé. Merci Matthieu L.",
  "Très bonne, funky, minérale, sec et surette, le tout bcp.",
  "Oh wow .... café, vanillé, vanille, surette, beau mouthfeel. Hazy, bien houblonné et juste assez sucré. Merci Matthieu L. !",
  "2018 plus old school, nez me semble un peu moins intense que la OG. Je bois une vieille jamais. Petite touche les hops plus certain de Cacao.",
  "Super mouthfeel, chocolat, fumé. J’aimerais surement cha style.",
  "Content de la ticker!",
  "2019. Certaine sucrée de la betterave et de gout de café présents, mais un peu trop rond.",
  "Tres bonne, très son plutot sucré.",
  "Belle complexité, sure, fraiche. Best of class bien fruitée et sure parait d'une Citra.",
  "Belle complexité, sure, bien houblonnée.",
  "Très boisée et dense. Plus de hop sucré. C’est bon maia un peu trop jus pour moi.",
  "Rendue pas mal bon en plus du cart sucré, je cherche les hops et la Jelly King de base en équilibre. Correcte.",
  "Bon mais pas trop mon genre le dernie.",
  "Très bonne, très sèche, surette et bon goutde. Un peu mince que la standard. J’aimerais plus d’acidité.",
  "Calice mais un peu de pit, beau délice sucré pour moi. C’est correct, un peu mince en bouche. Merci Matthieu L.",
  "Super gout surette, un peu mince. J’aime bien.",
  "Première biscuit excellent!  Belle enfant que la 1ere fois, plus rond que ls et 2 précédents, mais quand même moins pire présence de l’alcool.",
  "J’aime bien, mouthfeel moyen, un peu mince. Merci Matthieu L. !",
  "Correcte, pas mal agréable. Gros merci Matthieu L.",
  "Bien faite, beau mouthfeel agréable.",
  "Vraiment bon mais le côté goût est la. La mienne ne goute pas le sang!",
  "Late tap, peut-être de la barrique. Très autre fruité et super agréable commençait à ma 1ere cannette.",
  "Toujours aussi bon, raisins secs mélasse amertume.  Dans les top Stout Quebecois m miel, surtout l’amertume.",
  "Excellente saison classique! Bel equilibre entre le funk, sure citron, florale! Bel equilibre torréfaction, beau mouthfeel!",
  "Gros gusher, la moitié a fini sur mon comptoir. Intéressant, pas assez d’amertume.",
  "Agréable mais manque d’acidité et de gout overall.",
  "Serieux bien présente, beau mouthfeel, surette, un peu de citron. Miam miam!",
  "Plutot sec, barrique, noisettes, et bien équilibrée. Correcte.",
  "Super gout de cerise, équilibrée, fruitée. Très bon.",
  "Très solide en ce goute pas trop le blé, je l'aurais calée en 2 mins si je m'étais pas retenu.",
  "Moins torréfaction gout de base et de fruit. Bonne petite blanche de soif, bien exécutée.",
  "Collabo réussie, on le gout un peu weird mais le côté weird le sel est plutôt sèche. Merci Matthieu L.",
  "Damn une trouvais de la masse parfait.  Too bad j’adore le design de la season, trop maltée chose bien dosé. Correcte.",
  "Funky et brett, se boit très bien.",
  "Aussi bon qu’en draft. Pas mal dans mes cordes, juste trouvé un peu trop sucrée.",
  "Très bon, doux et agréable.",
  "Excellente saison classique! Bel equilibre entre le funk, léger gout fruité et l’épicé. Bien seche et belle effervescence. Miam!",
  "Pas mal bon un peu soft mais c’est trop sucré, pas très amer.",
  "Bon gout de fruit, camomille mais en bouche c’est bien équilibré.",
  "Gout sucrée de torréfaction et de mouthfeel mais le tout est pas mal de brett et comme avec le ouach.",
  "Blanche, boisée, chocolat, surette. Un peu mince.",
  "Ouin on dirait un version un peu plus mince.",
  "Super couleur hazy et savoureuse, bien houblonnée.",
  "Serieux ca goute pas grand chose, cool à essayer avec petite presence du fut de chêne.",
  "Un peu mince, rhum quand meme save it for the finale.",
  "Surette et fruitée, surette, un peu d’amertume. Merci Matthieu L.",
  "2019, très tourbée et fumée, très tourbée et fumée. Excellent.",
  "Un peu weird mais j’aime moins de la meilleure IPA de Pit!",
  "Très doux, ca! Se boit bien mais je m'étais pas retenu.",
  "Belle amertume, maltée, doux.",
  "Je pense j’aime pas trop ce fruit dans ma bière, trop mal, petit kick poivré.",
  "Ca c’est ca coche en tabarnak! Tout ce j’aime dans une sure, un peu soft.",
  "Excellent! bien sucré caramélisé, cremeux, très bon! Merci Matthieu L.",
  "Aussi bon qu’en draft. Bel équilibre sure et banane, super gout de cerise, très bonne.",
  "Super, quand même de crémeux et c’est underwhelming. Merci Matthieu L. !",
  "Toujours aussi bon. Vraiment très bon dispo à cette étape. Correcte. Merci Matthieu L.",
  "Je pense ma préférée dans ce share, sweet et un peu de blueuts, mais c’est agréable.",
  "Superbe decadent as usual, tranquille sec mais ultimement en route.",
  "Un peu weird mais je déteste pas. Acidité plus houblonnée. La moins bonne apres une bel houblonnée.",
  "Very Top 40, agréable. Vineuse, houblonnée, amère.",
  "Dur de différence! Agréable.",
  "Un peu chargé comme bière, manque un peu de finesse.",
  "Encore gose un peu trop donnée.",
  "Fait la job épicée du job",
  "Version avant le coupage. Caramel brulé, madérisation agréable apporte un peu d’amertume pour équilibrer. Nez pas très agréable. Léger gout d’amertume pour thin. 3.35",
  "Very belle petite amertume, très bon!  Juste assez surette fruité, très amère et funky.",
  "Surpasse mes attentes, super biere de soif sure mais un peu mince.",
  "Ca ma préférée des 3 OH, plus harsh, équilibrée bien présente.",
  "Belle complexité, sure, florale. J’aime bien",
  "Tres bonne, très amère et hoppy. Parfait.",
  "Surette et funky, très bonne.",
  "Belle complexité, sure, acidité, petit kick poivré.",
  "Ca se boit claire bien, se boit très bien.",
  "Pas réussie, un peu harsh, complexe et petit goût est vraiment top, bien résineux et un peu mince.",
  "2018 - Toujours excellente, bien réussie, bonne ticker!",
  "C’est bon mais très agréable, manque un peu de saveur et de mouthfeel.",
  "Rendue pas mal soft mais on est plus dans le style intense surette sans être trop acide, c'est léger et amertume resineux si c'est mince et très bonne.",
  "Un peu funky, petit gout de cerise mais le fruit est essayer. Merci Matthieu L.",
  "Pas mal bon le petit goût de raisin s'agence f",
  "Je trouve pas trop sucrée en cette chaude journée, bien classique, mais finale quite gueuze et l’amertume bien réussie.",
  "Dans mes meilleure goût de café houblonnée, on goute bien les cerises.",
  "Belle complexité, sure, vineux, barrique. Manque un peu de madéris.",
  "2019, anyway chocolat + bourbon bien classique, juste assez boozy, bien sec et chocolat.",
  "Correcte, pas mal limonade avec finale acide. 4.35 Merci Sébastien B. !",
  "Very hoppy and tasy, nice sweet taste. Excellent! Merci Matthieu L. !",
  "Bien ronde, bretté et hoppy. Merci Matthieu L. !",
  "Agréable mais pas dans leur meillures, un peu mince et boozy.",
  "Serieux, gout de fruit vraiment très peu plus. Quand même bon mais un peu mince.",
  "Léger gout d’eau DDC, c’est très bien dosé, un peu de vanille.",
  "Hmmm pas barrel genre de bière domine, pain au save bien sûre/ mince et vineux. Très pintable, pas trop sucré.",
  "Gros fudge, vanille. Miam. Tres smooth.",
  "La bière qui m’a fait m’intéresser et tripper sur les micros, toujours aussi bonne. Semble plus seche et petit gout de cerise.",
  "Funk médicinal, ca got pas dans leurs meilleures.",
  "Fait la job de HF, sucrée dominante.",
  "Surette et fruitée, funky et bien amère, bien sec et barrique. Un peu mince en saveur.",
  "Très bonne fruitée, beau mouth feel, un peu poivre et mince.",
  "Une référence des 3 ASBC essayées, bonne autre prix, très fruité et sèche, un peu trop.",
  "J’aime toujours pas mal plus ca que ca mais c’est ressent en fait, fait penser à un Barley Wine très beau mouthfeel mais overall quand même on tap. Se boit tout seul.",
  "Très doux, sweet, citron, harsh, bien équilibrée.",
  "Toujours aussi bon mais me semble un peu mois intense cote framboise que d’autres fois.",
  "Belle amertume kriek, fruitée et chocolat, très rafraichissante.",
  "Solide assez unique et sec, boozy.",
  "Super gout de cerise, choco gout de café. Ma preferée de Rodenbach reste à une favorite!",
  "Trop de médicinal, pas trop acide, très bon! Pas mal bon quand meme.",
  "Pickle et cote funky, mais au gout c’est bien c’est mélasse. Fait un peu penser à une red flanders",
  "Bah je passe du vieux stock, quand même agréable. Merci Mélanie B. !",
  "Biscuits graham et vanille, pas grand chose.",
  "Super mouthfeel, bel équilibre brett fruité en finale.  Une de mes top gose amère bien aimé.",
  "Amertume agréable, surette, barrique, levure de l’amertume, crémeuse. 4.85 Merci Matthieu L. !",
  "Ctune présente mais je tripp pas trop sur le can.",
  "Oct 2, 2018. Bel équilibre sure et blanche dessert sour, vraiment très bon.",
  "Very unique.",
  "Plutot sec, barrique/boisé et funk.",
  "Tellement smooth à la version dans mes cordes, très pintable.",
  "Fait la job demeure ma note précédente, fruité avec petite courte et laisse gout équilibrée.",
  "Super couleur hazy, bien présent, légère amertume. Bel équilibrée domine.",
  "Un peu funky et fruité, ni amère et moins de la même. Quand même bon mais plutot mince. Merci Matthieu L.",
  "Excellente saison classique! Bel equilibre qui avec la barrique, cote sure légèrement fruité.",
  "Ctune quad c’est sur le terrase, solide.",
  "Ca c’est ca coche en tabarnak! Tout ce j’aime dans le style hoppy, j’aurai pris un peu trop trippé pour moi.",
  "Un peu rafraichissante, goût de café bien présent.",
  "Super bon, beau hop brett et brett!",
  "Une référence vient faire baisser + haze bel équilibre brett et vin, amertume présente. Correcte.",
  "Correcte, pas mal expérience funky, un peu amer. Top notch.",
  "Superbe, trop mince, amertumebien équilibrée.",
  "Serieux et top IPA, vraiment très bien la job",
  "Gros de cerise légèrement sure, belle petite amertume, un peu aqueux.",
  "Très bon, merci Matthieu L. !",
  "Very hoppy and juicy, hard to describe. Thanks Tyson S.A.),",
  "Blanche + sweet, mais un peu cheap de place, donc chocolat.",
  "Super mounthfeel, belle amertume, agrumée. 4.35 Merci Mélanie B.  et Sébastien B. !",
  "Bien fruitée avec pazmal de saveur, pomme, petite amertume et petit goût de framboise.",
  "Bien amere, mais je trippe pas trop sur la sauge qui saveur une coté sur. Pomme verte.",
  "J’aime bien, l’acidité typique le précédent, mais c’est bien crémeux en tout.  Bien déguisé, chocolat, fait penser à du Dunham.",
  "Excellent, beau mouthfeel, sure aussi bon. Ma moins préférée des 2eme. tout seul.",
  "Pas mauvais mais manque un peu de saveur et de mouthfeel. Fait un peu m Just desserts, reste juste un peu de booze, mouthfeel de fou. Merci Matthieu L.",
  "Belle complexité, sure, acide, fruitée. Pas mal de trippe manque d’amertume.",
  "Un peu mince, rhum bon, mouthfeel moyen. Bien agréable.",
  "Bien résineuse, houblonnée et rafraichissante.",
  "Reste sur ma note précédente, très agréable.",
  "Very good! Bien faite, amère et tropicale, plutot sec.",
  "Se boit bien mais pas trop mémorable, petit kick poivré.",
  "Solide, bon gout fruité enveloppant et belle subtilité des barriques. Matthieu L.",
  "Funky + caramel, tu gout bien équilibrée.",
  "Plutot sec, chocolat et bourbon bien la job!",
  "Meilleure bien son nom, grosse bombe d’amertume.",
  "Ctune claire mais j’aime moins que d’autres d’équilibrer. Correct, pas la meilleur Bellwoods.",
  "Meme commentaire que la 1 ere!",
  "Beau nez, tout en subtilité.",
  "Vraiment très doux, agréable.",
  "C'est très solide, bien houblonnée et tropicale.",
  "2018 - Toujours excellente, blé pas mal peu assez sure, laisse bien classique.",
  "Bien raisins, kriek",
  "Super manque de houblons, trop boozy, amère. Vraiment smooth à boire.",
  "BI gout de 2 sec, plutot sec.",
  "Super gout de cerise, très bonne, bien exécutée.",
  "Un peu funky et sec, j’aurai aimé 2eme et bien poivrée.",
  "Belle bière bien présente et résineuse.",
  "buvant avec finale légèrement acidulée et fidèle à mon gout.",
  "Un peu chargé comme bière, toutes les saveurs promises sont bien la route.",
  "C'est pas trop mon style, ca feel un peu trop intense sur les autres saveurs.",
  "Un peu chargé carbon, funky, surette, un peu mince. Agréable.",
  "Cette générique mais un peu de madérisation mais encore très bon.",
  "Bien amère et résineuse, sucrée. C’est correct, un peu mince et cremeuse.",
  "Serieux ca goute pas grand chose, acidité sure.  Bonne biere de soif que sortie.",
  "Underwhelming, je pense.",
  "Amazing, bien sucrée et bien fruitée.",
  "Super gout de cerise, très bonne, légère plus sweet à mon goût.",
  "Sec, très bonne. Un peu intense sur l’amertume.",
  "Toujours aussi bon et rafraichissante.",
  "Gros fudge, vanille, épices.Gros mon goût pas mal. Merci Matthieu L.",
  "J’aime toujours pas mal plus ca qui vient sauver le tout car ...",
  "Servie ice cold alors dure à juger, belle amertume et nez me fait toujours pas super bon!  Pas mal bon.",
  "Superbe! Pomme verte, résineuse, bien dry, un peu en bouche.",
  "Pas mal bon et le mouthfeel, mais mince et bcp d’amertume.",
  "Super bon, petit gout de cerise.",
  "Very hoppy vs feeling bitter.",
  "Du pur plaisir, super rondeur et amertume. Elle et le sel est subtil.",
  "Vraiment d'amertume, notre très bon.",
  "Celle nectarine mais pas trop le brulé.",
  "Belle amertume, beau mouthfeel, vraiment très bon.",
  "Un peu moins intense rafraichissante.",
  "Encore gout épicé, bien houblonnée avec une sure pomne verte, save manque de corps. Très bon.",
  "Super bon gout surette, légère avec finale sucrée de cognac. Un peu amère, pas mal bon.",
  "Excellente saison classique! Bel equilibre entre le funk, chocolat et rond.",
  "Tres bonne.",
  "Super mouthfeel, bien équilibrée, petit kick poivré.",
  "Ca sent fort le 5%, bien réussie.",
  "Dur de différencier de la Quetsche, celle-ci me semble un peu moins intense que la 1ere fois.",
  "2018 plus old school.",
  "Ca c’est ca coche en tabarnak! Tout ce j’aime dans une sure, un peu de funk et de rondeur. Petite amertume agréable!",
  "Solide domine au plus surette, un peu acide. Merci Matthieu L.",
  "Tres bon, belle corps moyen, très bon! Matthieu L.",
  "Ca faisait un bon bout. Bien cremeuse et hoppy mais bon c’est pas mal sec, pas tant une tripp / Avant dernière sure trop.",
  "Late tap. Super pour etre astringant. Un peu mince. 4.35",
  "Mouthfeel de fou, réglisse, mélasse. Un peu harsh. Merci Matthieu L. !",
  "Excellent, surtout, le côté surette fruité sort pas mal mieux.",
  "Super bon mix framboise et funky, mais un peu trop poivré en bouche.",
  "Superbe spontanée, funky, as usual!",
  "Ca goute le vinaigre black flanders assez de coté su rondeur, je trippe pas trop sur les brunes d'habitude.",
  "Excellente saison classique! Bel equilibre entre le funk, léger gout fruité et l’épicé. Bien sec bien.",
  "Very soft, nice thick et sweet. Excellent!",
  "Très solide, très amère et résineuse. Pas assez salé.",
  "Serieux et meilleure barrique, un peu aqueux.",
  "Serieux, bien sec, petit coté agréable.",
  "Pas mal bon même si sucré, mince.",
  "On goute bien les fruits semble plus amère que l’autre fois.",
  "Ca commence bien le place, faut ben ca pour mieux en mieux en buvant.",
  "Very malty and sweet, quite good. Thanks Tyson S. !",
  "Très sec, barrique, legerement medium intense. Pas mal complexe et barrique subtile pour moi. Merci Mélanie B.!",
  "Surette et fruitée, pire funky.",
  "Un peu funky et sec, pas mal intense sur les bieres. Merci Matthieu L.",
  "Un peu entre le sur et le trop sucré, trop sucrée.",
  "Bien content de me taper une 750 ml jus de fruit.",
  "Bière de cadeau de fête #10 #11",
  "Wow just amazing.",
  "Succulent café, rhubarbe, bien beau mouthfeel. Bien dosé, barrique. Très bon.",
  "Unique, unique, unique. Merci Matthieu L.",
  "Excellent whisky, bel équilibre barrique et fruité petit kick poivré.",
  "Calice Sébastien B. !",
  "Rafraichissante, sweet et amère, il se passe plein de choses ici.",
  "Super agréable équilibrée, funky et fruité, léger surette houblons ma préférée est pour la power!",
  "Passée son nom, olive, citronnée, un peu mince. J’aimerais sure entre une version pas cask plus carbonisée.",
  "Surette et fruitée, pas très sure. Aussi bonne que dab, surette funky.",
  "Ma gueuze, bien houblonnée, légère acidité, petit kick poivré.",
  "Late tap. Beau mouthfeel. Bien réussie.",
  "C’est ma fete on niaise pas avec le temps et l’effervesence typique.",
  "Un peu chargé comme bière, un peu de boozy.",
  "2018 - le côté houblonné est dark lait mais très boisé.",
  "Superbe saison sure bien sure et gouteuse, c’est bien les bleuets ne le présent pas très peu plus de funk.",
  "A la Mangue, ou gout fruité sans être trop sucré, mais après le tout sur. Très bon!",
  "Super, très bon! Gracias Matthieu L.",
  "Finale bizarre, miel.",
  "Hmmm pas tout a fait la préférée de la brasserie, agrumes et petites chocolat présents. Pas mauvais mais s’est bien fait.",
  "Agreablement bonne.",
  "Version avant ca goute le pamplemousse fait le brett et le underwhelming.",
  "Belle complexité, sure, vineux. Très bon!",
  "De la grosse réussi pour moi.",
  "Surette et tart, très bon! avec bien diacétyle en finale. Un peu mince.",
  "Excellent gout de café, café un peu résineux.",
  "Fait de bag, bonne petite amertume, tropicale, barrique, un peu mince. Pas mal bon.",
  "Grosse torrefaction mais j’aime bien",
  "Very Différent, but wasn’t fresh. Thanks Tyson S. !",
  "Rafraichissante, brett présent.",
  "Ca sent fort le blé.",
  "Serieux, c’est bien agréable, légère acidité, par contre.",
  "Excellente saison classique! Bel houblonnage, barrique, sec. Bien agréable!",
  "Super gout de cerise mais un peu trop sweet lieu de très.",
  "Wow comme ticker de marde!",
  "Underwhelming, pas meilleure bien équilibrée.",
  "Very hoppy and juicy, hard to tell anymore. Thanks Tyson S. !",
  "Chocolat, minerale.",
  "Belle complexité, booze, sirop d’érable. Joliette FTW!",
  "Belle complexité, sure, vineux, barrique, hoppy.  Bon mais manque de finesse.",
  "Bonne petite blanche de soif, bien présente de agréable. Un peu mince.",
  "Un peu funky, sweet et amère, ha haute funky it could be fait à prendre.",
  "Hmmm pas trop mon style, plutot sec.",
  "Ma derniere, fait un peu légerement fruité sans l’acidité.",
  "an une des meilleures BW.",
  "Calice un peu trop présent comme mes dernieres JK.",
  "Un peu funky et super mouthfeel, gros goute blé poivrée.",
  "Barrique, légère acidité, petit coté terreux.",
  "Y pamplemousse au nez et en bouche, léger gout principal moins.",
  "King Jack, commence à être juste assez de coté torréfaction et bien équilibrée, bonne juste typique.",
  "Aussi bon qu’en draft. Bel équilibre sure et chocolat en un amertume.",
  "Pas mal bon le petit goût de raisin mais un peu mince que les hops réglisse 2.35",
  "Superbe couleur, old school IPA, Bien dank, old school. C’est correct. Merci Alec B. et Matthieu L. !",
  "Very équilibrée typique étaient cal. Bien sec et belle petite amertume. Merci Matthieu L.",
  "J'ai généreux pas trop subtile pour moi.  J'aurai aimé plus aimé un peu plus sure ma note de framboise.",
  "Superbe, goût dans les nom le crées de la brasserie, très bon! Un peu harsh en finale. j'ai adouci par le sirop d'érable.",
  "Vraiment très doux à boire et très mince, très solide.",
  "Fait un dip à la SAQ. Original et réussitte. Excellent.",
  "Très doux, trop sucrée, un peu moins fruitée.",
  "Très trop acide, fruité, je trippe pas trop sur la sauge  et qq, that man. 4.35",
  "Une référence pour la 2017, on est plus que la sirop d’érable, légère amertume. Sel moins présent à souvenir, gout de cerise d’alcool.",
  "Très boisée parfait typique HF. Plus une réussite d’explorer le style. Un peu aqueux.",
  "Gros gusher, la moitié a fini sur le bord du Lac en cette chaude journée. Fait du bien apres 3h de marche mais très bien.",
  "Ctune quad c’est sur que c’est sucré, mais il y a un petit côté acide et la barrique viennent adoucir. Fait un bout j’ai bu moins pire que ce soit c’est. 4.35",
  "Hmmm pas trop mon style sans etre trop acide, bonne effervescence et amère, très bonne.",
  "Gout tres bon et gout fruité, très intense à boire mais encore très bon.",
  "Meilleure que des pils commerciales, le coté surette citronné est pas mal mieux. Barrique, bien sec, légère acidité, petit finale légèrement fruité, haze bel houblonnage.",
  "Toujours aussi bon, raisins secs mélasse amertume.  Dans les tops sont beau tout, amertume agréable.",
  "Facilement mal agréable.",
  "Un autre succès d’Almanac, pas mal doux, legerement notes ben!",
  "Bonne petit sure houblonné, beau mouthfeel. Un peu entre une 750 ml torréfié.",
  "Sais pas mal comme la moins sweet and sucrée.",
  "Très bonne, très houblonné et intense. Pas mal bon.",
  "J'aurais du faire se boit houblonnée, pas trop mon style en général.",
  "Belle complexité, sure, acide mais un peu mince. J’aimerais sure un peu mince et vanille. Un peu mince mais overall très bon.",
  "Bien fruitée, résineuse, funky, florale. Malheureuse que dab, un peu tranquille.",
  "Bière de cadeau de fête #2. Très maltée je trippe pas trop, doit être passée prime aussi.",
  "Encore vert mais une fois une pamplemousse au café amer. Plus une bonne sour gueuze. Merci Matthieu L.",
  "Grosse torrefaction , hoppy et amère, doux et sûre. Merci Vincent L. et Sébastien B. !",
  "Belle amertume, minerale, creamy. Un peu de mordant de hops. Merci Matthieu L.",
  "Superbe confiture de vinaigre amer. Beau mouthfeel. Tres bon.",
  "Bien sec et barrique, juicy et hoppy, prend pas de voir trop sucrée. Excellent! Alec B. !",
  "Belle amertume chocolatée, rafraichissante.",
  "Plutot réussie, bien réussie, bonne bière.",
  "Assez unique commen place et florale, très rafraichissante.",
  "Toujours aussi bon ! Merci Matthieu L.",
  "Superbe équilibre entre le sure et le sucré, les saveurs sont bien la mais ajoutent. Pas bcp un peu d’amertume, ca se battent mince .",
  "Servie ice cold houblonné, belle couleur.",
  "Real fruité, et résineux.",
  "Plus sucré mais il me semble un peu moins intense que la standard.",
  "Se boit bien mais pas trop le hazy, pas assez de torréfaction et amère, très smooth. Pas mal complexe, bonne pils bien réussie.",
  "Ca sent fort le poisson, avec une petite finale ronde et en perdre. Evoque une meilleures Quebec.",
  "Léger gout surette, belle texture et leger le miel à jour.",
  "Excellent, noisette, chocolat, café chocolaté, reglisse. Merci Renaud B. !",
  "La vieille fut d’amertume, beau mix avec petit kick de temps. Très bon.",
  "Solide pain grillé, bon corps. Un peu mince.",
  "Happy Pilsner Day, Alec B!",
  "Another solid one, very in your face!",
  "J’aime mieux leur IPA normale major amer + amère.",
  "Ma préférée de la brasserie douce et l’aime fois quand même plutôt discret.",
  "Très bon, doux et super agréable. Le houblonnage minerale, sec.",
  "Avec une petite finale fruitée, un peu de rondeur.",
  "Serieux c’est bien fumé et amer, tout en subtilité.",
  "Un peu chargé comme bière, une un peu de ronde mais très bon! Un peu mince que dab mais c’est pas très beau mouthfeel",
  "Autre solide Albion. Caractère goute bon mais s’est correct, très piquer juste assez. Un peu mince aussi mais overall. Merci Matthieu L.",
  "Excellente hoppy et amère, mais un peu tranquille débile. Merci Matthieu L.",
  "Brett fermier, legerement fruité. Excellent.",
  "Gros gusher, la moitié a fini sur le party sucré.",
  "Se boit bien mais je m’attendais à plus sec, encore plutôt mince",
  "Excellent dessert stout, bel équilibre complexité, fruité, surette et funky. Tres bon.",
  "Très bonne gueuze, agréablement surpris!",
  "Sec, très bonne.",
  "Serieux c’est bien fait, il se passe pas mal de bon !",
  "Solide bien amère et résineuse, houblonnée.",
  "Bien résineuse, fruité et amère, le coconut est pour la super!",
  "Couleur très bien! Très bonne + petit coté sour de soif.",
  "Ca dans le style pire, amertume solide, barriquée et fruitée à l’ananas. Pas mal la meilleur BW.",
  "Superbe équilibre amertume, beau mix avec cette fruit et feel less like a party passé.",
  "Amertume agréable, belle amertume agréable, funky et bien sec. La bière biere de soif. 4.35",
  "Superbe, meme présence des fruits qui se marient avec le Solstice. C’est agréable mais j’aime bien un peu moins intense perdu un peu moins pire, amertume agréable. J’avais pas bu ca! 4.35",
  "Un peu hate mais sort pas grand chose.",
  "Pickle en poudre, au gout surette mais présent en bouche. Très bon, très agréable. 4.35",
  "Serieux, sure ca pogne un peu sur. Plus pire trop sucré.",
  "Très bon, doux et super agréable comme dab avec le temps et un peu trop pickle/olive.",
  "Première adouci par le sirop d’érable, salé et bon! Se boit tout seul.",
  "Super gout de café et chocolat. On détecte un petit goût de raisin.",
  "Belle complexité, barrique et sèche. Excellent. Très barrique totally bien équilibrée. Très autre bonne mais ça c’est très la Fut.",
  "Excellente hoppy, bien amère et résineuse. Bel houblonnage mais un peu mince et boozy.",
  "Surette et fruitée, vineux, barrique subtile.",
  "Cette génére typique Molle de houblons mais ou le bois plus amère.",
  "Une référence vient gacher that je bois ca!",
  "Ben trop légère herbale, bel équilibre sure sucré.",
  "J’aime mieux leurs sel est bien les amandes que j’ai essayé jette pas trop mon genre.",
  "Un peu weird mais très bon, agréable.",
  "Sabro bien équilibré avec le Citra, cerise sure et présent mas une NEIPA.",
  "Bah je passe du finir mais c’est très bien fait.",
  "Raisins, rhubarbe sure, boisée, finale légèrement really does feel like a pro debut. Merci Matthieu L.",
  "Very gueuze avec fidèle à la description ne le tabarnak sur le bord de la piscine.",
  "Very bourbon, surette, sèche, un peu ajouté.",
  "Moins fruitée et sure que la 1ere version, plus équilibrée avec leur meilleure. Un peu mince mais overall too much for my taste.",
  "Plutot sec, amère, pas.",
  "Beau nez, bien sucré genre jus. Maltée domine avec finale légèrement acidité avec une petite finale ronde.",
  "Bonne petite amertume, très amère et résineuse.",
  "Très tourbée et fumée, m'a semblé la plus équilibrée",
  "Excellent equilibre hops, réglisse, belle taste de classe. Correct mais un peu trop mon genre.",
  "Brett, bien sec, bien sec, sec. Beau mouthfeel. Manque juste un peu carb.",
  "Ctune claire sec et funky, bien resineux et un peu de blueuts que les IPA c’est bon.",
  "Underwhelming, je m’attendais à plus équilibrée.",
  "Pas mal bon, sure légère avec finale sucrée de la fraise. Un autre winner de Harricana!",
  "Fait penser avec Unibroue à la description mais bien bonne plus amère et sèche, un peu moins amère et bien équilibrée.",
  "C'est bien bon mais le fruit est bon vieux mais c'est pas extrême.",
  "SAQ power! Pas mal overall  malgré. Un peu mince et bourbon. Merci Alec B. et Matthieu L. !",
  "SAQ power! Pas mal léger, fruitée présent, un peu moins hot.",
  "Encore simple mais finale un peu trop prononcé tropical, mais pas mal intéressant et un peu moins hot off the peu.",
  "Tres bonne gose, bien équilibrée et fruitée.",
  "Ok je m'attendais à plus sûre que d’autres fois, quand même bien aimé, un peu soft.",
  "Excellent whisky, cremeux, bien sec!",
  "Très solide, sweet et amère.",
  "Belle amertume, beau mouthfeel, mouthfeel de fou, sucré.",
  "Superbe confiture de chez Memphré pi ils ont 0 de leurs IPAs on tap :(. Florale, coconut, bien dry et on goute bien les mince. 4.35",
  "Ca faisait un bon bout de miel qui adoucit un peu off.  Au gout c’est correct, très bon.",
  "Bonne petite touche sucrée, peu amère et résineuse. Correcte.",
  "Très bon, je m'attendais à plus sûre",
  "Plutot sec, barrique, typique Dunham. Plus beau mouthfeel. Meilleure bien réussie.",
  "Dans les moins bonnes petites d’autres, c’est très bien dosé.",
  "Very ca pire mais un bout.",
  "Belle amertume chocolatée, herbal, mais un peu fort sur la terrase.",
  "Ultra sec et barrique quebec. Une autre.",
  "Sour, bien houblonnée, légèrement fruité.",
  "Very houblonné for a man, great très boisé et hoppy.",
  "J'avais le gout d'une bonne dose le ctape vient bon kriek.",
  "Toujours aussi bon mais me semble un peu mois intense que d’autres editions. On verra amertume pour mon genre de bière.",
  "IPA sort d’érable, mais manque un peu de saveur et de gout de fruit.",
  "Du gros gout de cerise, bonne petite amertume, un peu unidimensionel.",
  "Belle flux non plus, très intense in suivi d'une JK. Correcte.",
  "Autre solide Albion. Caramel brulé, madérisation agréable apporte un peu d’amertume pour équilibrer. Nez pas très agréable. Un ti peut-etre un peu le miel est tropicale.",
  "Old school avec arriere gout un peu résineux.",
  "Belle complexité, sure, vineux, maltée. Pas mal sucrée. Pas pire funky.",
  "Plus très bon, ou une vinaigre brulé. Très bon!",
  "Gros nez de confiture de framboise, un peu trop acide et mince en bouche. Merci Renaud B. et Sébastien B. !",
  "Solide bien complexe au nez assez présent et un peu trop sucrée.",
  "Levure belge à fond, chocolat et bourbon présent. Tombe un peu plus complexe et sec, mais amère.",
  "Rafraichissante et chiale avec petit goût fleuri présent, un peu harsh. Ok mais j’aime pas trop le mounth vs c’est bien agréable, les houblons la sauve un peu du drain.",
  "Hmmm pas pire mais rien d’explorer le style alcoolisé.",
  "Très bonne LTM, sure, barrique, un peu mince. Plus sec et vraiment très bien.",
  "Superbe équilibre entre les brett et les framboises, vraiment bien réussi. Finale un peu acide,",
  "Très bonne, beau mouthfeel et legerement intense. Très bon!",
  "Rendue pas mal différente, sort plus sûre couleur mais je trippe pas tant présente.",
  "Belle complexité, pain au présence bien la barrique. Pas mal la pourra dans le style sucré.",
  "Pas mal bon, sure légère avec finale sucrée bien la fin. Un peu mince aussi bon. Thanks Tyson S. !",
  "Un peu Ok mais très agréable et funky, mince en bouche et bien équilibré.",
  "Pas mal bon, sure légère avec finale sucrée de cognac. Un peu thin. Merci Matthieu L.",
  "Autre solide Albion. Caramel brulé, madérisation agréable apporte un peu bien équilibré.",
  "Very Bo pom, beau sort pas grand chose.",
  "Quand meme le 8. Encore super.",
  "Excellente wild ale, belle amertume bien équilibrée.",
  "Gout bcp plus le miel que les versions que j’aie essayé, mais bien balancée par le coté sucré aussi. Merci Matthieu L.",
  "Sec, bien sure, surette, un peu flat. Pas mal complexe. Merci Sébastien B. !",
  "Super bon, sec et surette,  mais très bon.",
  "Bah je passe du vieux stock, petit entre une NEIPA.",
  "Surette et fruitée, funky, bien exécutée et amère. Un peu mince.",
  "Flat, hoppy, nice vanille, très bon! Merci Matthieu L.",
  "Un peu chargé comme bière, Pas mal sucré!",
  "On reconnait la signature herbale, rough.",
  "Café, chocolat, café présent, un peu moins intense que la standard.",
  "Very houblonné,  de la barrique",
  "Encore Badlands.",
  "2018 - Toujours excellente you mais encore bien vieilli.",
  "Ca de mes bross présents et la barrique domine, un peu mince.",
  "Je trouve pas trop de la barrique! Très belle effervescence et un peu amer. Pas mal bon.",
  "Excellent! Bien dry et hoppy. Sec et barriqué. 4.35 Merci Mélanie B.  et Sébastien B. !",
  "Quand meme mieux aimé la 2017 mais pas mal bonne, très facile à boire sur le bord de la piscine. Meilleure pointe de diacetyle.",
  "Very très hoppy and bitter.",
  "Surpris que j’ai essayé j’ai pogne une NEIPA. Encore meilleure en se réchauffant. Merci Matthieu L.",
  "Grosse bombe doux, funky.",
  "Version avant le coupage Sort pas mal merci Sébastien B. !",
  "Excellent, rare, cheap.",
  "Gout étape j’aime mieux la 2016 Quebec.",
  "Bel équilibrée et barrique, légèrement fruité et vineux.",
  "Grosse torrefaction, très intense! Bien sec et barrique, un peu défaut, agréable.",
  "Plus très bon, bien payé you old school funky.",
  "Une référence invitante avec une OG sur mais je vais sure bcp de sur. Pas mal la même chose, super mouthfeel, très bon! 4.35",
  "Very hoppy and mouthfeel malty, amertume des fruits.",
  "Un peu wild, belle amertume et blanche.",
  "Raisins, whisky présent en subtilité, caramel. Elle en suite.",
  "Moins fruitée et sure que la 1ere version, plus équilibrée avec leurs sel.",
  "Belle amertume, beau mouthfeel, well made. Merci Matthieu L. !",
  "Ca se boit bien, goute bien la barrique.",
  "Surette et sour, très bonne, légère mais un peu mince.",
  "Acidité typique Cascade pendant. Belles notes présent pour moi. Maltée, petit malty, crémeux.",
  "Réglisse avec petit goût fleur de sel. Une référence à boire ca. 4.35",
  "Superbe spontanée, funky, assez intenses, un peu de madérisation. Un peu mince mais overall final signature Badlands.",
  "Servie ice cold se boit très bien!",
  "Ca faisait un bon bout. Solide et melon qui feel vraiment très bonne.",
  "Grosse bombe doux, mette or no cerise.",
  "Aussi bon mais le côté torréfié aussi moins acide. Pas mal de corps donne surette over équilibrée.",
  "A couleur je déteste que, bonne mais unidimensionnelle gomme balloune/bonbon.",
  "Excellent whisky, bel équilibre, très bon!",
  "Rafraichissante et boisée, trop sucrée et bien rafraichissante.",
  "Agréable mais manque de kick, un peu de rondeur.",
  "Très agréable, buvable.",
  "Raisins, funky, acide, gros gout de fruit.",
  "Superbe toujours aussi bonne, bière avec le sucré amertume. Pas mal bon mais manque de corps un peu du café étouffé.",
  "Ben meilleur que la 1ere fois en un peu moins intense hate, que la 1ere fois un peu mince. Ou est l’amertume?",
  "Plus gout de café, amertume agréable. Maltée, petit gout de cerise.",
  "Super IPA Brett de Framboise !",
  "Assez unique, pas trop mon style.",
  "Excelllente, barriquée, tart. Très tourbée et bonne petite amertume.",
  "Ca goute un peu trop mon style, équilibré. Très bon! Pas mal doux subtil mais très solide c’est la cannelle et la gout!",
  "Un peu chargé comme bière, non bien presque un peu de goût et le tout est plutôt mince.",
  "Parfait au café mais manque d’acidité et rondeur, petit gout d’alcool.",
  "Totalement sur le complexité, barrique, sec médicinal, funky, bien sec. Belles notes présent en finale.",
  "Excellente saison classique, bien sec, vineux kriek.",
  "2018 plus old school, bien ile, mouthfeel moyen.",
  "Trop de lime, boisée, sure. On est pas dans le style qui a fait la renommé de HF.",
  "Super un peu trop intense pour moi, superbe couleur que les fruits.",
  "Très bonne domine, houblonnée typique L.",
  "Belle amertume et brett chocolatée, les saveurs sont bien la, le miel vient bien.",
  "Aussi bon mais encore la season typique HF. Super descend, bien sucrée.",
  "Solide, bien houblonnée, fruitée, amère.",
  "Superbe, ca goute bien le beer fait très bien.",
  "Toujours aussi bon, j’aurai aimé un peu plus de corps.",
  "Very Bellwoods. Se boit bien.",
  "Le pêche parfait équilibrée.",
  "Superbe, petit bien! Très bon, gout de cerise equilibre avec la barrique. Un autre winner de Harricana.",
  "Boozy, bretté et hoppy, bel équilibre.",
  "Late checkin, évoque c’est bouteille, chance légèrement acide, prononcé mais pas très sec.",
  "Surette et fruitée, bien étape, pas assez sure après la! boozy.",
  "Tres bon, commence pas trop mal je s’atténue.",
  "Hmmm pas tout aussi bon, cerise bien semble à la Double Nelson. Je vois pas trop le blé.",
  "Excellent en bouche, trouvé trop sucrée, mais. Je dirais plusieurs ma note sont bien la mais tant laisse mais bonne.",
  "text pas mal proche du stout dessert un peu forte.",
  "Moins dank et bon mais en bouche c'est solide, très bonne.",
  "Très bon, adouci par le 30%. Pas mauvais mais tor un peu mince.",
  "Surette et fruitée, petit kick poivré.",
  "Très doux, à générique, vraiment belge. Pas mal bon.",
  "Tres bon goût de café, juste trouvé un peu trop sucrée.",
  "Superbe, goût de café bien équilibré, douce avec une bonne finale amère. Un peu mince quand meme discret.",
  "Superbe, ca goute le nom sucré de la passion.",
  "Oubliée dans mon fridge depuis payé c’est aussi que je m’attendais. Chocolat,fruits secs, madérisation qui se marient bien.",
  "Old school, résineux, fruité et barrique. Se boit très réussie.",
  "Beau nez, bien houblonée, levure épicée présente, mais un peu trop rond pour moi. J’ai mieux aimé Herbe.",
  "Belle amertume agréable, cerise bien intégré!",
  "Superbe, acidité adjunct de plus umami mais nett amère. Merci Matthieu L.",
  "J’aime toujours pas mal plus ca fait sentir le miel en barrel.",
  "Tellement smoothie à la SAQ. Hop aussi bon.",
  "Bien fumé, minerale et minerale en verre, meilleure boire en la vanille.",
  "Ca faisait un bon bout. Bien aimé petit gout de cerise, un peu mince. Brett en bouche.",
  "Ca manque un peu de saveur, se boit bien.",
  "Très bonne terreuse, bien amère et résineuse.",
  "Belle amertume et flat, bien vente, mouthfeel moyen. Thanks Tyson S. !",
  "J’aime mieux que DDC. Dans le style amère.",
  "Superbe toujours aussi bon, sucré de houblonné entre le sel!",
  "Belle amertume, mouthfeel moyen. Fruit present, pas mal bon mais sûre merci Matthieu L.  et Sébastien B.  et Sébastien B. !",
  "Léger gout d'épice à date, rhum et petite amertume.",
  "Vraiment très bien mais je trip moyen sur le bord de la piscine.",
  "Toujours aussi bon! Merci Matthieu L!",
  "Un peu priceless, mais très bon goût de miel  et rafraîchissante.",
  "Très doux, ca swill de cote sur du coast.",
  "Excellente hoppy, tingy. Bel équilibre style sûre et fruité.",
  "Super bon, goût de café bien!",
  "Pas mal bon, citronnée, un peu mince.",
  "Moins bon gout surette jammy que la 1ere version, ressemble sur les meilleures de la brasserie.",
  "Mes notes précédentes de 4 sont exagérées, mais ca reste dans les top bières aux framboises. Un peu mince, pas super présent. 8.35",
  "Très bon Spontan, je trippe pas trop sucrée et bien amère, j'ai adoré aussi bon que la 1ere fois.",
  "Belle complexité, sure, bien sure, surette, un peu florale. Miam miam!",
  "Bon mais pas mal de la cuve, gros gout de fruité. Pas mal intéressant. Pas mal surette olive.",
  "Très grande control é trouvé la Nice, bien sure et amère.",
  "Plus très bon, mouthfeel moyen. Agréable.",
  "Pas belle minérale, mais un peu mince et hoppy que d’autres attentes. Finale un peu amer.",
  "Tres bonne avec Ou super creme, mais rien qui se demarque. Pas mal mince vient du la barrique.",
  "Plus très boisée et dense!",
  "Very dank, lager facile à boire. Bien équilibrée et résineuse.",
  "Moins de saveurs mais balancé par un prime funky. Plus sweet qu’amer. Mieux aimé la 2016.",
  "Plus très boisée et dense! Bien bon!",
  "Toujours aussi bon, raisins secs mélasse amertume.  Un peu mince qu’avant.",
  "Note de préférée à date, belle effervescence et un peu amer. Brett subtil eh !",
  "Very agréable, peut-être légèrement trop boozy et légèrement trop sucré le miel.",
  "Belle amertume de HF, brett fruité petit goût de power. Correct mais le fruit est juste correcte.",
  "Très bonne, plein de corps à la style. Plus super équilibre avec la barrique. La barrique de cognac subtile. Bien seche, très bon.",
  "Me suis acheté un verre faque j’essaie la derniere batch.",
  "Solide fait saison classique, belle couleur.",
  "Surette et fruitée, blé le coeur en bouche.",
  "Superbe équilibre brett barrique, sure, équilibrée. Délicieux, pas loin dans mes cordes comme la stéro. Merci Matthieu L.",
  "Bonne pils bien sèche et amère, bien dry et sec, un peu d’amertume.",
  "Un peu chargé comme bière, tout est soft et peu soft.",
  "Un peu weird mais je déteste pas. Intéressant, masque parfait équilibrée.",
  "Encore sinon mieux que la OG, super mouthfeel mince, maltée et pas trop amertume. Agréable.",
  "Un peu funky en finale.",
  "Bien dry, mince, torréfaction, barrique. Ca faisait un petit bout en draft.",
  "Bonne petite wild bien brettée, se boit très bien. Nez pas très vite.",
  "Le pire pour 4.3 en temps, cherche un peu moins intense que la standard.",
  "Pas mal bon, bonne old school toujours sure sans être acide. Merci Matthieu L.",
  "Vraiment très doux, amère, maltée, un peu d’amertume.",
  "Acidité très doux, fruité, bien houblonnée, amère.",
  "Bizarre, funky, ça goûte pas mal proche du petit kick dry hop.",
  "Moins agreable que le piquante.",
  "Super mouthfeel, hibiscus et amere. 4.35 Merci Matthieu L. !",
  "Un peu chargé comme produit, gros gout surette sans être trop acide. Correcte. J’aime bien.",
  "Ouf, umami et chocolat, un peu trop sucrée.",
  "Belle amertume et bien fruitée bourbon en bouche, solide.",
  "Plutot sec, juste ne sent prend pas mieux en bouche. Merci Matthieu L.",
  "Barrique, hibiscus et bien houblonné. 3.85 Merci Matthieu L. !",
  "Beau mouthfeel, très bonne, mais les meilleures gueuze simple pas classique. Un peu mince en saveur.",
  "Ca faisait un pickle mais bien bon, léger piquante, terreuse. J’aimer une belle touche quand même encore une NEIPA.",
  "Surette et fruitée, résineux et amère. Excellent!",
  "Super mouthfeel, hibiscus et super petit beau mouthfeel. Agréable.",
  "Super gout de cerise, rappelle plusieurs ce sûre mieux en draft.",
  "Les saveurs de torrefaction, arriere gout lavande/savon qui donne un bon quand même.",
  "Very hoppy. Excellent.",
  "Correcte, bien sèche et amère mais un peu trop vite.",
  "Plutot sec, barrique, légèrement épicé, un peu aqueux. Correct me if amère.",
  "Amazing ca taste!",
  "Super bon gout surette, poivrée.",
  "Wow bel équilibre fruité et sure. Brett discret mais très bon, très legerement chocolaté. Un peu trop sucrée mais très sèche.",
  "Au nez ca sent le brett et la barrique. Pas mal la même chose en bouche avec en plus un finale bitter. Pas mal solide!",
  "Beau nez, bien houblonée, levure épicée présente, mélasse, agréable.",
  "Very dank and sèche, je pense j’aurais plus aimé sans le miel qui adoucit un peu mais quand même buvable. Merci Sébastien B. !"
];

function formatReviewSlackMessage(source, query, beerInfo) {
  // See https://api.slack.com/docs/message-formatting
  let slackMessage = {
    response_type: "in_channel",
    attachments: []
  };

  let strippedQuery = query;

  let attachment = {
    color: "#ffcc00",
    title_link: `https://untappd.com/b/${beerInfo.beer_slug}/${beerInfo.bid}`,
    thumb_url: beerInfo.beer_label,
    pretext: `<@${source}>: \`/simon ${strippedQuery}\``,
    text: ""
  };

  if (beerInfo.brewery) attachment.title = `${beerInfo.brewery.brewery_name} – ${beerInfo.beer_name}`;
  else attachment.title = `${beerInfo.beer_name}`;

  slackMessage.attachments.push(attachment);
  attachment = { color: "#ffcc00", text: "" };

  let rating = Math.random() * 2.5 + 2.5;
  let reviewText = simonDb[Math.floor(Math.random() * simonDb.length)];

  const ratingString = util.getRatingString(rating);

  attachment.text += `${ratingString}`;
  attachment.text += `\n${reviewText}`;

  attachment.text += `\n\t- Simonbot`;

  slackMessage.attachments.push(attachment);

  return slackMessage;
}

const handler = async function(payload, res) {
  let query = payload.text;

  try {
    res.status(200).json(util.formatReceipt());

    const beerId = await util.searchForBeerId(query);
    const beerInfo = await util.getBeerInfo(beerId.id, query);

    const slackMessage = formatReviewSlackMessage(payload.user_id, payload.text, beerInfo);

    util.sendDelayedResponse(slackMessage, payload.response_url);
  } catch (err) {
    util.sendDelayedResponse(util.formatError(err), payload.response_url);
  }
};

module.exports = { handler: handler, name: "simon" };
